use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use regex::Regex;
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};

const SITE_IMAGE_ROOT: &str = "assets/images";
const GENERATED: &str = "Generated by harness-kit-checks build-docs-site; do not edit manually.";

#[derive(Debug, Clone)]
pub struct CheckOptions {
    pub repo_root: PathBuf,
    pub site: PathBuf,
    pub compare_to_rebuild: bool,
}

pub fn default_site(repo_root: &Path) -> PathBuf {
    repo_root.join("docs/site")
}

pub fn validate_site(options: &CheckOptions) -> Result<()> {
    let repo = &options.repo_root;
    let site = &options.site;
    if !site.exists() {
        bail!(
            "{}: missing; run harness-kit-checks build-docs-site",
            site.display()
        );
    }

    let copy = load_copy(repo)?;
    let expected = expected_primitives(repo)?;
    let mut seen: BTreeMap<String, Vec<PathBuf>> = BTreeMap::new();
    let mut source_seen: BTreeMap<String, Vec<PathBuf>> = BTreeMap::new();
    for page in glob_html(&site.join("reference"))? {
        if page.parent() == Some(&site.join("reference")) {
            continue;
        }
        let (primitive, source) = page_metadata(&page)?;
        if let Some(primitive) = primitive {
            seen.entry(primitive).or_default().push(page.clone());
        }
        if let Some(source) = source {
            source_seen
                .entry(source.clone())
                .or_default()
                .push(page.clone());
            if !repo.join(&source).exists() {
                bail!("{}: stale source link {source}", page.display());
            }
        }
    }

    let expected_keys: BTreeSet<_> = expected.keys().cloned().collect();
    let seen_keys: BTreeSet<_> = seen.keys().cloned().collect();
    let missing: Vec<_> = expected_keys.difference(&seen_keys).cloned().collect();
    if !missing.is_empty() {
        bail!("missing primitive page(s): {}", missing.join(", "));
    }
    let extra: Vec<_> = seen_keys.difference(&expected_keys).cloned().collect();
    if !extra.is_empty() {
        bail!("unexpected primitive page(s): {}", extra.join(", "));
    }
    let duplicates: Vec<_> = seen
        .iter()
        .filter_map(|(key, paths)| (paths.len() != 1).then_some(key.clone()))
        .collect();
    if !duplicates.is_empty() {
        bail!("duplicate primitive page(s): {}", duplicates.join(", "));
    }
    let duplicate_sources: Vec<_> = source_seen
        .iter()
        .filter_map(|(key, paths)| (paths.len() != 1).then_some(key.clone()))
        .collect();
    if !duplicate_sources.is_empty() {
        bail!("duplicate source link(s): {}", duplicate_sources.join(", "));
    }

    let manifest_path = site.join("manifest.json");
    let manifest: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path)
            .with_context(|| format!("failed to read {}", manifest_path.display()))?,
    )
    .with_context(|| format!("{}: invalid JSON", manifest_path.display()))?;
    if manifest.get("copy_source").and_then(Value::as_str) != Some("docs/copy/site.json") {
        bail!(
            "{}: copy_source must be docs/copy/site.json",
            manifest_path.display()
        );
    }
    let manifest_ids: Vec<_> = array(&manifest, "primitives")
        .iter()
        .filter_map(|item| item.get("id").and_then(Value::as_str).map(str::to_string))
        .collect();
    if manifest_ids.iter().cloned().collect::<BTreeSet<_>>() != expected_keys {
        bail!(
            "{}: primitive manifest does not match source catalog",
            manifest_path.display()
        );
    }
    for item in array(&manifest, "primitives") {
        let id = item.get("id").and_then(Value::as_str).unwrap_or("unknown");
        let page = string_field(item, "page", &manifest_path)?;
        let source = string_field(item, "source", &manifest_path)?;
        if !site.join(&page).exists() {
            bail!("{}: page missing for {id}: {page}", manifest_path.display());
        }
        if !repo.join(&source).exists() {
            bail!(
                "{}: source missing for {id}: {source}",
                manifest_path.display()
            );
        }
    }
    validate_images(repo, &copy, &manifest, site)?;

    for relative in [
        "index.html",
        "concepts.html",
        "workflows.html",
        "governance.html",
        "reference/index.html",
        "reference/gates.html",
        "reference/bootstrap.html",
        "llms.txt",
        ".nojekyll",
    ] {
        let path = site.join(relative);
        if !path.exists() {
            bail!("{}: missing required page", path.display());
        }
        let text = fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        if relative.ends_with(".html") && !text.contains(GENERATED) {
            bail!("{}: missing generated marker", path.display());
        }
    }

    let workflows = array(&copy, "workflows");
    if workflows.len() < 5 {
        bail!(
            "{}: expected at least five workflows",
            copy_source(repo).display()
        );
    }
    let expected_workflow_pages: BTreeSet<_> = workflows
        .iter()
        .filter_map(|item| item.as_object())
        .map(|item| {
            format!(
                "{}.html",
                slug(item.get("title").and_then(Value::as_str).unwrap_or(""))
            )
        })
        .collect();
    let workflow_pages = direct_html_files(&site.join("workflows"))?;
    let workflow_page_names: BTreeSet<_> = workflow_pages
        .iter()
        .filter_map(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .map(str::to_string)
        })
        .collect();
    if workflow_page_names != expected_workflow_pages {
        bail!(
            "{}: workflow pages do not match docs/copy/site.json",
            site.join("workflows").display()
        );
    }
    for page in workflow_pages {
        let text = fs::read_to_string(&page)
            .with_context(|| format!("failed to read {}", page.display()))?;
        for phrase in [
            "Input",
            "Decision",
            "Evidence",
            "Failure handling",
            "What to verify",
        ] {
            if !text.contains(phrase) {
                bail!("{}: missing workflow section {phrase}", page.display());
            }
        }
    }

    let icons_path = site.join("assets/icons.svg");
    if !icons_path.exists() {
        bail!("{}: missing generated icon sprite", icons_path.display());
    }
    let icons_text = fs::read_to_string(&icons_path)
        .with_context(|| format!("failed to read {}", icons_path.display()))?;
    let manifest_icons: BTreeSet<_> = array(&manifest, "icons")
        .iter()
        .filter_map(|value| value.as_str().map(str::to_string))
        .collect();
    for icon in required_icons(&copy, &manifest) {
        if !manifest_icons.contains(&icon) {
            bail!(
                "{}: icon {icon} is used but missing from manifest icons",
                manifest_path.display()
            );
        }
        if !icons_text.contains(&format!("id=\"icon-{icon}\"")) {
            bail!("{}: missing symbol for icon {icon}", icons_path.display());
        }
    }

    for path in all_files(site)? {
        let text = fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        for pattern in private_patterns()? {
            if pattern.is_match(&text) {
                bail!(
                    "{}: generated docs contain private or local-only text matching {}",
                    path.display(),
                    pattern.as_str()
                );
            }
        }
    }

    if options.compare_to_rebuild {
        let temp = tempfile::tempdir().context("failed to create temporary directory")?;
        let rebuilt = temp.path().join("site");
        let output = Command::new("cargo")
            .args([
                "run",
                "--locked",
                "-p",
                "harness-kit-checks",
                "--",
                "build-docs-site",
                "--output",
            ])
            .arg(&rebuilt)
            .current_dir(repo)
            .output()
            .context("failed to run harness-kit-checks build-docs-site")?;
        if !output.status.success() {
            bail!(
                "harness-kit-checks build-docs-site failed: {}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
        }
        let issues = compare_dirs(&rebuilt, site)?;
        if !issues.is_empty() {
            bail!(
                "docs/site is stale:\n{}",
                issues.into_iter().take(40).collect::<Vec<_>>().join("\n")
            );
        }
    }
    Ok(())
}

pub fn self_test(repo: &Path) -> Result<()> {
    validate_site(&CheckOptions {
        repo_root: repo.to_path_buf(),
        site: default_site(repo),
        compare_to_rebuild: true,
    })?;
    let copy = load_copy(repo)?;
    let images = image_declarations(repo, &copy)?;
    let skill_pages = direct_html_files(&repo.join("docs/site/reference/skills"))?;
    if skill_pages.is_empty() {
        bail!("self-test needs at least one generated skill page");
    }

    mutate_site_expect_failure(repo, "missing generated skill page", |base| {
        let page = direct_html_files(&base.join("reference/skills"))?
            .into_iter()
            .next()
            .context("missing copied skill page")?;
        fs::remove_file(page)?;
        Ok(())
    })?;
    mutate_site_expect_failure(repo, "duplicate generated primitive page", |base| {
        let page = direct_html_files(&base.join("reference/skills"))?
            .into_iter()
            .next()
            .context("missing copied skill page")?;
        fs::copy(&page, page.with_file_name("duplicate.html"))?;
        Ok(())
    })?;
    mutate_site_expect_failure(repo, "stale source link", |base| {
        let page = direct_html_files(&base.join("reference/skills"))?
            .into_iter()
            .next()
            .context("missing copied skill page")?;
        let text = fs::read_to_string(&page)?;
        let replaced = Regex::new(r#"<meta name="harness-kit-source" content="[^"]+">"#)?
            .replace(
                &text,
                r#"<meta name="harness-kit-source" content="missing/source.md">"#,
            )
            .to_string();
        fs::write(page, replaced)?;
        Ok(())
    })?;

    if !images.is_empty() {
        mutate_site_expect_failure(repo, "missing generated image", |base| {
            let image = all_files(&base.join(SITE_IMAGE_ROOT))?
                .into_iter()
                .next()
                .context("missing copied image")?;
            fs::remove_file(image)?;
            Ok(())
        })?;
        mutate_site_expect_failure(repo, "generated image byte drift", |base| {
            let image = all_files(&base.join(SITE_IMAGE_ROOT))?
                .into_iter()
                .next()
                .context("missing copied image")?;
            let mut text = fs::read_to_string(&image)?;
            text.push_str("\n<!-- drift -->\n");
            fs::write(image, text)?;
            Ok(())
        })?;
        mutate_site_expect_failure(repo, "empty or mismatched image alt", |base| {
            let page = base.join(string_field(&images[0], "page", &copy_source(repo))?);
            let text = fs::read_to_string(&page)?;
            let replaced = Regex::new(r#"alt="[^"]+""#)?
                .replace(&text, r#"alt="""#)
                .to_string();
            fs::write(page, replaced)?;
            Ok(())
        })?;
        mutate_site_expect_failure(repo, "missing text-equivalent anchor", |base| {
            let page = base.join(string_field(&images[0], "page", &copy_source(repo))?);
            let anchor = string_field(&images[0], "text_equivalent_anchor", &copy_source(repo))?;
            let text = fs::read_to_string(&page)?
                .replace(&format!("id=\"{anchor}\""), "id=\"missing-anchor\"");
            fs::write(page, text)?;
            Ok(())
        })?;
        mutate_site_expect_failure(repo, "undeclared html image", |base| {
            let page = base.join(string_field(&images[0], "page", &copy_source(repo))?);
            let text = fs::read_to_string(&page)?.replacen(
                "</section>",
                r#"<img src="../assets/images/undeclared.svg" alt="Undeclared">
</section>"#,
                1,
            );
            fs::write(page, text)?;
            Ok(())
        })?;
        mutate_site_expect_failure(repo, "stale generated image", |base| {
            fs::write(
                base.join(SITE_IMAGE_ROOT).join("stale.svg"),
                r#"<svg xmlns="http://www.w3.org/2000/svg"/>"#,
            )?;
            Ok(())
        })?;

        expect_copy_failure(repo, "missing source policy", |copy| {
            array_mut(copy, "images")?[0]
                .as_object_mut()
                .context("image must be object")?
                .remove("source_policy");
            Ok(())
        })?;
        expect_copy_failure(repo, "missing review note", |copy| {
            array_mut(copy, "images")?[0]["review_note"] = json!("");
            Ok(())
        })?;
        expect_copy_failure(repo, "image path traversal", |copy| {
            array_mut(copy, "images")?[0]["source"] = json!("../secrets.svg");
            Ok(())
        })?;
        expect_copy_failure(repo, "unused image declaration", |copy| {
            array_mut(copy, "images")?[0]["page"] = json!("workflows/missing.html");
            Ok(())
        })?;
        expect_copy_failure(repo, "image size overflow", |copy| {
            array_mut(copy, "images")?[0]["max_bytes"] = json!(1);
            Ok(())
        })?;

        let temp = tempfile::tempdir().context("failed to create temporary directory")?;
        let copied_repo = temp.path().join("repo");
        copy_repo_for_self_test(repo, &copied_repo)?;
        let copy_path = copied_repo.join("docs/copy/site.json");
        let mut data: Value = serde_json::from_str(&fs::read_to_string(&copy_path)?)?;
        data.as_object_mut()
            .context("docs copy root must be object")?
            .remove("images");
        fs::write(&copy_path, serde_json::to_string_pretty(&data)? + "\n")?;
        let image_root = copied_repo.join("docs/copy/images");
        if image_root.exists() {
            fs::remove_dir_all(image_root)?;
        }
        run_checked(
            Command::new("cargo")
                .args([
                    "run",
                    "--locked",
                    "-p",
                    "harness-kit-checks",
                    "--",
                    "build-docs-site",
                ])
                .current_dir(&copied_repo),
            "harness-kit-checks build-docs-site",
        )?;
        run_checked(
            Command::new("cargo")
                .args([
                    "run",
                    "--locked",
                    "-p",
                    "harness-kit-checks",
                    "--",
                    "check-docs-site",
                    "--repo",
                    ".",
                ])
                .current_dir(&copied_repo),
            "harness-kit-checks check-docs-site",
        )?;
    }
    Ok(())
}

pub fn build_site(repo: &Path, output: &Path) -> Result<()> {
    let copy = load_copy(repo)?;
    let primitives = render_primitives(repo)?;
    let gates = collect_gates(repo)?;
    let backlog = collect_backlog(repo)?;
    let images = image_declarations(repo, &copy)?;
    if output.exists() {
        fs::remove_dir_all(output)
            .with_context(|| format!("failed to remove {}", output.display()))?;
    }
    fs::create_dir_all(output)?;

    write_file(
        output,
        "index.html",
        &page(
            "Start",
            "index.html",
            &format!(
                r#"<section><p class="eyebrow">Harness Kit</p><h1>Harness Kit generated documentation</h1><p>This site is generated from the live repository.</p><p>Skills: {}. Agents: {}. Gates: {}.</p></section>"#,
                primitives
                    .iter()
                    .filter(|primitive| primitive.kind == "skill")
                    .count(),
                primitives
                    .iter()
                    .filter(|primitive| primitive.kind == "agent")
                    .count(),
                gates.len()
            ),
        ),
    )?;
    write_file(
        output,
        "concepts.html",
        &page(
            "Concepts",
            "concepts.html",
            "<section><h1>Concepts</h1><p>Harness Kit keeps skills, agents, gates, and operating doctrine source-backed.</p></section>",
        ),
    )?;
    write_file(
        output,
        "workflows.html",
        &page(
            "Workflows",
            "workflows.html",
            &render_workflows_index(&copy),
        ),
    )?;
    for workflow in array(&copy, "workflows") {
        if let Some(workflow) = workflow.as_object() {
            let title = workflow.get("title").and_then(Value::as_str).unwrap_or("");
            let path = format!("workflows/{}.html", slug(title));
            write_file(
                output,
                &path,
                &page(title, &path, &render_workflow_page(repo, &copy, workflow)?),
            )?;
        }
    }
    write_file(
        output,
        "governance.html",
        &page(
            "Governance",
            "governance.html",
            "<section><h1>Governance</h1><p>Provider output is evidence, not authority. Completion claims require live artifacts.</p></section>",
        ),
    )?;
    write_file(
        output,
        "reference/index.html",
        &page(
            "Reference",
            "reference/index.html",
            &render_reference_index(&primitives, &gates),
        ),
    )?;
    write_file(
        output,
        "reference/gates.html",
        &page(
            "CI Gates",
            "reference/gates.html",
            &render_gates_page(&gates),
        ),
    )?;
    write_file(
        output,
        "reference/bootstrap.html",
        &page(
            "Bootstrap",
            "reference/bootstrap.html",
            r#"<section><h1>Bootstrap behavior</h1><p>harness-kit-checks bootstrap installs system-wide harness links and provider roster files; bootstrap.sh is the curl-compatible launcher.</p></section>"#,
        ),
    )?;
    for primitive in &primitives {
        write_file(output, &primitive.page, &render_primitive_page(primitive))?;
    }
    for image in &images {
        let output_path = output.join(string_field(image, "output", &copy_source(repo))?);
        fs::create_dir_all(
            output_path
                .parent()
                .context("image output missing parent")?,
        )?;
        fs::copy(
            repo.join(string_field(image, "source", &copy_source(repo))?),
            output_path,
        )?;
    }
    write_file(
        output,
        "manifest.json",
        &render_manifest(repo, &copy, &primitives, &gates, &backlog, &images)?,
    )?;
    write_file(
        output,
        "llms.txt",
        &render_llms(&primitives, &gates, &images)?,
    )?;
    write_file(output, ".nojekyll", "")?;
    write_file(
        output,
        "assets/site.css",
        &format!(
            "/* {GENERATED} */\nbody{{font-family:system-ui,sans-serif;line-height:1.5;margin:0;color:#111827;background:#fbfcff}}main,header{{max-width:1100px;margin:auto;padding:24px}}nav a{{margin-right:12px}}section{{margin:24px 0}}.card{{border:1px solid #d9dee8;border-radius:8px;padding:16px;margin:12px 0;background:white}}code{{background:#eef5ff;padding:2px 5px;border-radius:4px}}img{{max-width:100%;height:auto}}.source{{color:#5b6575}}\n"
        ),
    )?;
    write_file(output, "assets/catalog.js", &format!("// {GENERATED}\n"))?;
    write_file(
        output,
        "assets/icons.svg",
        &render_icons(&copy, &primitives)?,
    )?;
    Ok(())
}

#[derive(Debug, Clone)]
struct RenderPrimitive {
    kind: String,
    name: String,
    description: String,
    source: String,
    page: String,
    role: String,
    icon: String,
}

impl RenderPrimitive {
    fn id(&self) -> String {
        format!("{}:{}", self.kind, self.name)
    }
}

fn render_primitives(repo: &Path) -> Result<Vec<RenderPrimitive>> {
    let role_icons = load_copy(repo)?
        .get("role_icons")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let mut primitives = Vec::new();
    for (id, source) in expected_primitives(repo)? {
        let (kind, name) = id
            .split_once(':')
            .context("primitive id must contain kind prefix")?;
        let role = if kind == "agent" {
            "Specialist".to_string()
        } else {
            workflow_role(name).to_string()
        };
        let icon = role_icons
            .get(&role)
            .and_then(Value::as_str)
            .unwrap_or("catalog")
            .to_string();
        primitives.push(RenderPrimitive {
            kind: kind.to_string(),
            name: name.to_string(),
            description: primitive_description(&repo.join(&source))?,
            source,
            page: format!("reference/{}s/{}.html", kind, slug(name)),
            role,
            icon,
        });
    }
    primitives.sort_by_key(|primitive| primitive.id());
    Ok(primitives)
}

fn primitive_description(path: &Path) -> Result<String> {
    let text = fs::read_to_string(path)?;
    if let Some(frontmatter) = text
        .strip_prefix("---\n")
        .and_then(|rest| rest.split_once("\n---"))
    {
        let lines: Vec<_> = frontmatter.0.lines().collect();
        let mut index = 0;
        while index < lines.len() {
            let line = lines[index];
            if let Some((key, raw)) = line.split_once(':')
                && key.trim() == "description"
            {
                let raw = raw.trim();
                if raw == "|" {
                    let mut parts = Vec::new();
                    index += 1;
                    while index < lines.len() && lines[index].starts_with("  ") {
                        parts.push(lines[index].trim());
                        index += 1;
                    }
                    return Ok(parts.join(" "));
                }
                return Ok(raw.trim_matches('"').trim_matches('\'').to_string());
            }
            index += 1;
        }
    }
    Ok(text
        .lines()
        .find_map(|line| line.strip_prefix("# ").map(str::trim))
        .unwrap_or_else(|| {
            path.file_stem()
                .and_then(|name| name.to_str())
                .unwrap_or("item")
        })
        .to_string())
}

fn workflow_role(name: &str) -> &'static str {
    match name {
        "shape" | "groom" => "Plan",
        "implement" => "Build",
        "deliver" => "Orchestrate",
        "code-review" => "Review",
        "ci" | "qa" => "Verify",
        "refactor" => "Improve",
        "ship" | "yeet" => "Ship",
        "flywheel" | "monitor" => "Operate",
        "reflect" => "Learn",
        "harness-engineering" => "Maintain",
        "research" => "Explore",
        "diagnose" => "Repair",
        _ => "Support",
    }
}

fn collect_gates(repo: &Path) -> Result<Vec<String>> {
    let text = fs::read_to_string(repo.join("ci/src/harness_kit_ci/main.py"))?;
    let regex = Regex::new(r#"run_gate,\s+"([^"]+)""#)?;
    let mut gates = regex
        .captures_iter(&text)
        .filter_map(|captures| captures.get(1).map(|value| value.as_str().to_string()))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>();
    gates.sort();
    Ok(gates)
}

fn collect_backlog(repo: &Path) -> Result<Vec<Value>> {
    let mut rows = Vec::new();
    let backlog = repo.join("backlog.d");
    if !backlog.exists() {
        return Ok(rows);
    }
    for entry in fs::read_dir(backlog)? {
        let path = entry?.path();
        if path.extension().and_then(|value| value.to_str()) != Some("md") {
            continue;
        }
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if !name
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_digit())
        {
            continue;
        }
        let text = fs::read_to_string(&path)?;
        let title = text
            .lines()
            .next()
            .unwrap_or(name)
            .trim_start_matches('#')
            .trim();
        rows.push(json!({
            "title": title,
            "source": path.strip_prefix(repo)?.to_string_lossy().replace('\\', "/"),
        }));
    }
    rows.sort_by(|left, right| {
        left["source"]
            .as_str()
            .unwrap_or("")
            .cmp(right["source"].as_str().unwrap_or(""))
    });
    Ok(rows)
}

fn page(title: &str, current: &str, body: &str) -> String {
    let css = path_between_pages(current, "assets/site.css");
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="{generated}">
  <title>{title} | Harness Kit Docs</title>
  <link rel="stylesheet" href="{css}">
</head>
<body>
  <header><a href="{home}">Harness Kit</a><nav><a href="{concepts}">Concepts</a><a href="{workflows}">Workflows</a><a href="{governance}">Governance</a><a href="{reference}">Reference</a></nav></header>
  <main>
{body}
  </main>
</body>
</html>
"#,
        generated = escape_html(GENERATED),
        title = escape_html(title),
        css = escape_html(&css),
        home = escape_html(&path_between_pages(current, "index.html")),
        concepts = escape_html(&path_between_pages(current, "concepts.html")),
        workflows = escape_html(&path_between_pages(current, "workflows.html")),
        governance = escape_html(&path_between_pages(current, "governance.html")),
        reference = escape_html(&path_between_pages(current, "reference/index.html")),
        body = body
    )
}

fn render_workflows_index(copy: &Value) -> String {
    let mut html = String::from("<section><h1>Workflows</h1>");
    for workflow in array(copy, "workflows") {
        let title = workflow.get("title").and_then(Value::as_str).unwrap_or("");
        let summary = workflow
            .get("summary")
            .and_then(Value::as_str)
            .unwrap_or("");
        html.push_str(&format!(
            r#"<article class="card"><h2>{}</h2><p>{}</p><a href="workflows/{}.html">Open workflow</a></article>"#,
            escape_html(title),
            escape_html(summary),
            escape_html(&slug(title))
        ));
    }
    html.push_str("</section>");
    html
}

fn render_workflow_page(
    repo: &Path,
    copy: &Value,
    workflow: &Map<String, Value>,
) -> Result<String> {
    let title = workflow.get("title").and_then(Value::as_str).unwrap_or("");
    let current = format!("workflows/{}.html", slug(title));
    let mut html = format!(
        r#"<section><h1>{}</h1><p>{}</p><p class="source">Source: {}</p></section><section><h2>Input</h2><p>{}</p><h2>Decision</h2><p>{}</p><h2>Evidence</h2><p>{}</p><h2>Failure handling</h2><p>{}</p></section>"#,
        escape_html(title),
        escape_html(
            workflow
                .get("summary")
                .and_then(Value::as_str)
                .unwrap_or("")
        ),
        escape_html(workflow.get("source").and_then(Value::as_str).unwrap_or("")),
        escape_html(workflow.get("input").and_then(Value::as_str).unwrap_or("")),
        escape_html(
            workflow
                .get("decision")
                .and_then(Value::as_str)
                .unwrap_or("")
        ),
        escape_html(
            workflow
                .get("evidence")
                .and_then(Value::as_str)
                .unwrap_or("")
        ),
        escape_html(
            workflow
                .get("failure")
                .and_then(Value::as_str)
                .unwrap_or("")
        ),
    );
    for image in image_declarations(repo, copy)? {
        if string_field(&image, "page", &copy_source(repo))? != current {
            continue;
        }
        let output = string_field(&image, "output", &copy_source(repo))?;
        let items = image["text_equivalent_items"]
            .as_array()
            .unwrap_or(&Vec::new())
            .iter()
            .map(|item| format!("<li>{}</li>", escape_html(item.as_str().unwrap_or(""))))
            .collect::<Vec<_>>()
            .join("");
        html.push_str(&format!(
            r#"<section><figure><img src="{}" alt="{}"><figcaption>{}</figcaption></figure><div id="{}"><h2>{}</h2><ul>{}</ul><p>{} Regeneration: {}</p></div></section>"#,
            escape_html(&path_between_pages(&current, &output)),
            escape_html(&string_field(&image, "alt", &copy_source(repo))?),
            escape_html(&string_field(&image, "review_note", &copy_source(repo))?),
            escape_html(&string_field(&image, "text_equivalent_anchor", &copy_source(repo))?),
            escape_html(&string_field(&image, "text_equivalent_heading", &copy_source(repo))?),
            items,
            escape_html(&string_field(&image, "source_policy", &copy_source(repo))?),
            escape_html(&string_field(&image, "regeneration_ref", &copy_source(repo))?),
        ));
    }
    html.push_str("<section><h2>What to verify</h2><ul><li>The input exists in live evidence.</li><li>The decision has an oracle.</li><li>The evidence path is captured before closeout.</li></ul></section>");
    Ok(html)
}

fn render_reference_index(primitives: &[RenderPrimitive], gates: &[String]) -> String {
    let mut html = format!(
        "<section><h1>Reference</h1><p>{} primitives and {} gates generated from source.</p></section>",
        primitives.len(),
        gates.len()
    );
    html.push_str("<section>");
    for primitive in primitives {
        html.push_str(&format!(
            r#"<article class="card"><h2>{}</h2><p>{}</p><code>{}</code><p>{}</p><a href="{}">Reference</a></article>"#,
            escape_html(&primitive.name),
            escape_html(&primitive.kind),
            escape_html(&if primitive.kind == "skill" { format!("/{}", primitive.name) } else { primitive.name.clone() }),
            escape_html(&primitive.description),
            escape_html(&path_between_pages("reference/index.html", &primitive.page))
        ));
    }
    html.push_str("</section>");
    html
}

fn render_gates_page(gates: &[String]) -> String {
    let mut html = String::from("<section><h1>CI gate map</h1>");
    for gate in gates {
        html.push_str(&format!(
            r#"<article class="card"><h2>{}</h2><p>Runs as part of dagger call check --source=.</p></article>"#,
            escape_html(gate)
        ));
    }
    html.push_str("</section>");
    html
}

fn render_primitive_page(primitive: &RenderPrimitive) -> String {
    let body = format!(
        r#"<section data-primitive-id="{}"><h1>{}</h1><p>{}</p><p><code>{}</code></p><p class="source">Source: {}</p></section><section><h2>What to verify</h2><ul><li>The source file exists and carries valid frontmatter.</li><li>The primitive has one generated reference page.</li><li>Claims trace back to the linked source.</li></ul></section>"#,
        escape_html(&primitive.id()),
        escape_html(&primitive.name),
        escape_html(&primitive.description),
        escape_html(&if primitive.kind == "skill" {
            format!("/{}", primitive.name)
        } else {
            primitive.name.clone()
        }),
        escape_html(&primitive.source)
    );
    page(
        &format!("{}: {}", primitive.kind, primitive.name),
        &primitive.page,
        &body,
    )
    .replace(
        "<meta name=\"generator\"",
        &format!(
            "<meta name=\"harness-kit-primitive\" content=\"{}\">\n  <meta name=\"harness-kit-source\" content=\"{}\">\n  <meta name=\"generator\"",
            escape_html(&primitive.id()),
            escape_html(&primitive.source)
        ),
    )
}

fn render_manifest(
    repo: &Path,
    copy: &Value,
    primitives: &[RenderPrimitive],
    gates: &[String],
    backlog: &[Value],
    images: &[Value],
) -> Result<String> {
    let primitive_rows = primitives
        .iter()
        .map(|primitive| {
            json!({
                "id": primitive.id(),
                "kind": primitive.kind,
                "name": primitive.name,
                "description": primitive.description,
                "source": primitive.source,
                "page": primitive.page,
                "role": primitive.role,
                "icon": primitive.icon,
            })
        })
        .collect::<Vec<_>>();
    let image_rows = images
        .iter()
        .map(|image| image_manifest_row(repo, image))
        .collect::<Result<Vec<_>>>()?;
    Ok(serde_json::to_string_pretty(&json!({
        "generated_by": "harness-kit-checks build-docs-site",
        "copy_source": "docs/copy/site.json",
        "do_not_edit": true,
        "icons": required_icons(copy, &json!({"primitives": primitive_rows, "workflows": array(copy, "workflows")})).into_iter().collect::<Vec<_>>(),
        "primitives": primitive_rows,
        "onboarding": {
            "quickstart": copy["home"]["quickstart"].clone(),
            "task_finder": copy["home"]["task_finder"].clone(),
        },
        "workflows": array(copy, "workflows"),
        "images": image_rows,
        "gates": gates,
        "backlog": backlog,
    }))? + "\n")
}

fn render_llms(
    primitives: &[RenderPrimitive],
    gates: &[String],
    images: &[Value],
) -> Result<String> {
    let mut lines = vec![
        "# Harness Kit generated docs context".to_string(),
        String::new(),
        GENERATED.to_string(),
        "Copy source: docs/copy/site.json".to_string(),
        String::new(),
        "Primitives:".to_string(),
    ];
    for primitive in primitives {
        lines.push(format!(
            "- {} | {} | docs/site/{}",
            primitive.id(),
            primitive.source,
            primitive.page
        ));
    }
    lines.push(String::new());
    lines.push("Docs figures:".to_string());
    for image in images {
        lines.push(format!(
            "- {} | {} -> docs/site/{} | text: #{} | {}",
            image["page"].as_str().unwrap_or(""),
            image["source"].as_str().unwrap_or(""),
            image["output"].as_str().unwrap_or(""),
            image["text_equivalent_anchor"].as_str().unwrap_or(""),
            image["alt"].as_str().unwrap_or("")
        ));
    }
    lines.push(String::new());
    lines.push("CI gates:".to_string());
    lines.extend(gates.iter().map(|gate| format!("- {gate}")));
    Ok(lines.join("\n") + "\n")
}

fn render_icons(copy: &Value, primitives: &[RenderPrimitive]) -> Result<String> {
    let manifest = json!({
        "primitives": primitives.iter().map(|primitive| json!({"icon": primitive.icon})).collect::<Vec<_>>(),
        "workflows": array(copy, "workflows"),
    });
    let mut html = format!(
        "<!-- {GENERATED} -->\n<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"display:none\">\n"
    );
    for icon in required_icons(copy, &manifest) {
        html.push_str(&format!(
            "<symbol id=\"icon-{}\" viewBox=\"0 0 24 24\"><path d=\"M4 4h16v16H4z\"/></symbol>\n",
            escape_html(&icon)
        ));
    }
    html.push_str("</svg>\n");
    Ok(html)
}

fn write_file(output: &Path, relative: &str, content: &str) -> Result<()> {
    let path = output.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn copy_source(repo: &Path) -> PathBuf {
    repo.join("docs/copy/site.json")
}

fn copy_image_root(repo: &Path) -> PathBuf {
    repo.join("docs/copy/images")
}

fn load_copy(repo: &Path) -> Result<Value> {
    let path = copy_source(repo);
    if !path.exists() {
        bail!("{}: missing docs copy source", path.display());
    }
    let text =
        fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?;
    for pattern in private_patterns()? {
        if pattern.is_match(&text) {
            bail!(
                "{}: copy source contains private or local-only text matching {}",
                path.display(),
                pattern.as_str()
            );
        }
    }
    let data: Value =
        serde_json::from_str(&text).with_context(|| format!("{}: invalid JSON", path.display()))?;
    for key in ["home", "concepts", "governance", "workflows", "role_icons"] {
        if data.get(key).is_none() {
            bail!("{}: missing required key {key}", path.display());
        }
    }
    Ok(data)
}

fn image_declarations(repo: &Path, copy: &Value) -> Result<Vec<Value>> {
    let images = copy
        .get("images")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    if copy.get("images").is_some_and(|value| !value.is_array()) {
        bail!("{}: images must be list", copy_source(repo).display());
    }
    let workflow_pages: BTreeSet<_> = array(copy, "workflows")
        .iter()
        .filter_map(|item| item.as_object())
        .map(|item| {
            format!(
                "workflows/{}.html",
                slug(item.get("title").and_then(Value::as_str).unwrap_or(""))
            )
        })
        .collect();
    let mut declarations = Vec::new();
    let mut seen_sources = BTreeSet::new();
    let mut seen_outputs = BTreeSet::new();
    let mut seen_anchors = BTreeSet::new();
    let stable_anchor = Regex::new(r"^[a-z][a-z0-9-]*$")?;
    for (index, raw) in images.into_iter().enumerate() {
        let Some(object) = raw.as_object() else {
            bail!(
                "{}: images[{index}] must be object",
                copy_source(repo).display()
            );
        };
        let mut image = Value::Object(object.clone());
        for key in [
            "page",
            "source",
            "alt",
            "text_equivalent_anchor",
            "text_equivalent_heading",
            "text_equivalent_items",
            "source_policy",
            "review_note",
            "regeneration_ref",
        ] {
            if image.get(key).is_none() {
                bail!(
                    "{}: images[{index}] missing {key}",
                    copy_source(repo).display()
                );
            }
        }
        let page = string_field(&image, "page", &copy_source(repo))?;
        let source = string_field(&image, "source", &copy_source(repo))?;
        let anchor = string_field(&image, "text_equivalent_anchor", &copy_source(repo))?;
        if !workflow_pages.contains(&page) {
            bail!(
                "{}: images[{index}] targets unknown workflow page {page}",
                copy_source(repo).display()
            );
        }
        let source_path = Path::new(&source);
        if !source.starts_with("docs/copy/images/")
            || source_path.is_absolute()
            || source_path
                .components()
                .any(|component| component.as_os_str() == "..")
        {
            bail!(
                "{}: images[{index}] source must stay under docs/copy/images/",
                copy_source(repo).display()
            );
        }
        let absolute_source = repo.join(&source);
        if !absolute_source.exists() {
            bail!("{source}: declared image source is missing");
        }
        let suffix = absolute_source
            .extension()
            .and_then(|value| value.to_str())
            .unwrap_or("")
            .to_ascii_lowercase();
        if !matches!(suffix.as_str(), "svg" | "png" | "jpg" | "jpeg" | "webp") {
            bail!("{source}: unsupported image extension");
        }
        let max_bytes = match image.get("max_bytes") {
            Some(Value::Number(number)) => number.as_i64().unwrap_or(-1),
            Some(Value::String(text)) => text.parse::<i64>().unwrap_or(-1),
            Some(_) => -1,
            None => 250 * 1024,
        };
        if max_bytes <= 0 {
            bail!(
                "{}: images[{index}] max_bytes must be positive",
                copy_source(repo).display()
            );
        }
        let source_size = absolute_source.metadata()?.len() as i64;
        if source_size > max_bytes {
            bail!("{source}: {source_size} bytes exceeds max_bytes {max_bytes}");
        }
        if !stable_anchor.is_match(&anchor) {
            bail!(
                "{}: images[{index}] text_equivalent_anchor must be a stable HTML id",
                copy_source(repo).display()
            );
        }
        let Some(items) = image.get("text_equivalent_items").and_then(Value::as_array) else {
            bail!(
                "{}: images[{index}] text_equivalent_items must be non-empty strings",
                copy_source(repo).display()
            );
        };
        if items.is_empty()
            || items
                .iter()
                .any(|item| item.as_str().unwrap_or("").trim().is_empty())
        {
            bail!(
                "{}: images[{index}] text_equivalent_items must be non-empty strings",
                copy_source(repo).display()
            );
        }
        for text_key in [
            "alt",
            "text_equivalent_heading",
            "source_policy",
            "review_note",
            "regeneration_ref",
        ] {
            if string_field(&image, text_key, &copy_source(repo))?
                .trim()
                .is_empty()
            {
                bail!(
                    "{}: images[{index}] {text_key} must be non-empty",
                    copy_source(repo).display()
                );
            }
        }
        let output = format!(
            "{SITE_IMAGE_ROOT}/{}",
            absolute_source
                .file_name()
                .and_then(|name| name.to_str())
                .context("image source missing file name")?
        );
        if !seen_sources.insert(source.clone())
            || !seen_outputs.insert(output.clone())
            || !seen_anchors.insert((page.clone(), anchor.clone()))
        {
            bail!(
                "{}: images[{index}] duplicates an image source, output, or anchor",
                copy_source(repo).display()
            );
        }
        image["output"] = json!(output);
        image["max_bytes"] = json!(max_bytes);
        declarations.push(image);
    }
    let declared_sources: BTreeSet<_> = declarations
        .iter()
        .filter_map(|image| {
            image
                .get("source")
                .and_then(Value::as_str)
                .map(str::to_string)
        })
        .collect();
    let root = copy_image_root(repo);
    if root.exists() {
        let undeclared: Vec<_> = all_files(&root)?
            .into_iter()
            .filter_map(|path| {
                let relative = path
                    .strip_prefix(repo)
                    .ok()?
                    .to_string_lossy()
                    .replace('\\', "/");
                (!declared_sources.contains(&relative)).then_some(relative)
            })
            .collect();
        if !undeclared.is_empty() {
            bail!(
                "{}: undeclared source image(s): {}",
                root.strip_prefix(repo).unwrap_or(&root).display(),
                undeclared.join(", ")
            );
        }
    }
    Ok(declarations)
}

fn image_manifest_row(repo: &Path, image: &Value) -> Result<Value> {
    let source = string_field(image, "source", &copy_source(repo))?;
    let data = fs::read(repo.join(&source))?;
    Ok(json!({
        "page": string_field(image, "page", &copy_source(repo))?,
        "source": source,
        "output": string_field(image, "output", &copy_source(repo))?,
        "alt": string_field(image, "alt", &copy_source(repo))?,
        "text_equivalent_anchor": string_field(image, "text_equivalent_anchor", &copy_source(repo))?,
        "text_equivalent_heading": string_field(image, "text_equivalent_heading", &copy_source(repo))?,
        "text_equivalent_items": image["text_equivalent_items"].as_array().unwrap_or(&Vec::new()).iter().map(|item| Value::String(item.as_str().unwrap_or("").to_string())).collect::<Vec<_>>(),
        "source_policy": string_field(image, "source_policy", &copy_source(repo))?,
        "review_note": string_field(image, "review_note", &copy_source(repo))?,
        "regeneration_ref": string_field(image, "regeneration_ref", &copy_source(repo))?,
        "max_bytes": image["max_bytes"].as_i64().unwrap_or(0),
        "bytes": data.len(),
        "sha256": format!("{:x}", Sha256::digest(&data)),
    }))
}

fn validate_images(repo: &Path, copy: &Value, manifest: &Value, site: &Path) -> Result<()> {
    let declarations = image_declarations(repo, copy)?;
    let expected_rows: Vec<_> = declarations
        .iter()
        .map(|image| image_manifest_row(repo, image))
        .collect::<Result<_>>()?;
    if manifest
        .get("images")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
        != expected_rows
    {
        bail!(
            "{}: image manifest does not match docs/copy/site.json",
            site.join("manifest.json").display()
        );
    }
    let expected_outputs: BTreeSet<_> = expected_rows
        .iter()
        .filter_map(|row| {
            row.get("output")
                .and_then(Value::as_str)
                .map(str::to_string)
        })
        .collect();
    let generated_image_root = site.join(SITE_IMAGE_ROOT);
    if generated_image_root.exists() {
        let extra: Vec<_> = all_files(&generated_image_root)?
            .into_iter()
            .filter_map(|path| {
                let relative = path
                    .strip_prefix(site)
                    .ok()?
                    .to_string_lossy()
                    .replace('\\', "/");
                (!expected_outputs.contains(&relative)).then_some(relative)
            })
            .collect();
        if !extra.is_empty() {
            bail!(
                "{}: unexpected generated image(s): {}",
                generated_image_root.display(),
                extra.join(", ")
            );
        }
    } else if !expected_outputs.is_empty() {
        bail!(
            "{}: missing generated image directory",
            generated_image_root.display()
        );
    }

    for (image, row) in declarations.iter().zip(expected_rows.iter()) {
        let output = site.join(string_field(image, "output", &copy_source(repo))?);
        let source = repo.join(string_field(image, "source", &copy_source(repo))?);
        if !output.exists() {
            bail!("{}: declared generated image is missing", output.display());
        }
        if fs::read(&output)? != fs::read(&source)? {
            bail!(
                "{}: generated image bytes drift from {}",
                output.display(),
                string_field(image, "source", &copy_source(repo))?
            );
        }
        let page = site.join(string_field(image, "page", &copy_source(repo))?);
        if !page.exists() {
            bail!("{}: image target page is missing", page.display());
        }
        let text = fs::read_to_string(&page)?;
        let src = path_between_pages(
            &string_field(image, "page", &copy_source(repo))?,
            &string_field(image, "output", &copy_source(repo))?,
        );
        let matches: Vec<_> = html_img_srcs(&text)
            .into_iter()
            .filter(|(found_src, _)| found_src == &src)
            .collect();
        if matches.len() != 1 {
            bail!(
                "{}: declared image {src} must be used exactly once",
                page.display()
            );
        }
        if matches[0].1 != string_field(image, "alt", &copy_source(repo))? {
            bail!(
                "{}: image alt text does not match docs/copy/site.json",
                page.display()
            );
        }
        let anchor = string_field(image, "text_equivalent_anchor", &copy_source(repo))?;
        if !text.contains(&format!("id=\"{anchor}\"")) {
            bail!(
                "{}: missing text-equivalent anchor {anchor}",
                page.display()
            );
        }
        for key in [
            "review_note",
            "text_equivalent_heading",
            "source_policy",
            "regeneration_ref",
        ] {
            let value = string_field(image, key, &copy_source(repo))?;
            if !text.contains(&value) {
                bail!("{}: missing image {key}", page.display());
            }
        }
        for item in row["text_equivalent_items"]
            .as_array()
            .unwrap_or(&Vec::new())
        {
            let value = item.as_str().unwrap_or("");
            if !text.contains(value) {
                bail!("{}: missing image text-equivalent item", page.display());
            }
        }
    }

    let mut allowed_srcs_by_page: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for image in &declarations {
        let page = string_field(image, "page", &copy_source(repo))?;
        let src = path_between_pages(&page, &string_field(image, "output", &copy_source(repo))?);
        allowed_srcs_by_page.entry(page).or_default().insert(src);
    }
    for page in glob_html(site)? {
        let relative_page = page
            .strip_prefix(site)?
            .to_string_lossy()
            .replace('\\', "/");
        let allowed = allowed_srcs_by_page
            .get(&relative_page)
            .cloned()
            .unwrap_or_default();
        for (src, _) in html_img_srcs(&fs::read_to_string(&page)?) {
            if !allowed.contains(&src) {
                bail!("{}: undeclared img src {src}", page.display());
            }
        }
    }
    Ok(())
}

fn required_icons(copy: &Value, manifest: &Value) -> BTreeSet<String> {
    let mut icons = BTreeSet::new();
    if let Some(home) = copy.get("home").and_then(Value::as_object) {
        for item in home
            .get("start_cards")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            if let Some(icon) = item.get("icon").and_then(Value::as_str) {
                icons.insert(icon.to_string());
            }
        }
    }
    for section in ["concepts", "governance"] {
        let key = if section == "concepts" {
            "items"
        } else {
            "cards"
        };
        if let Some(object) = copy.get(section).and_then(Value::as_object) {
            for item in object
                .get(key)
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                if let Some(array) = item.as_array()
                    && let Some(icon) = array.get(2).and_then(Value::as_str)
                {
                    icons.insert(icon.to_string());
                }
            }
        }
    }
    for workflow in array(copy, "workflows") {
        if let Some(icon) = workflow.get("icon").and_then(Value::as_str) {
            icons.insert(icon.to_string());
        }
    }
    if let Some(role_icons) = copy.get("role_icons").and_then(Value::as_object) {
        for value in role_icons.values() {
            if let Some(icon) = value.as_str() {
                icons.insert(icon.to_string());
            }
        }
    }
    for primitive in array(manifest, "primitives") {
        if let Some(icon) = primitive.get("icon").and_then(Value::as_str) {
            icons.insert(icon.to_string());
        }
    }
    for workflow in array(manifest, "workflows") {
        if let Some(icon) = workflow.get("icon").and_then(Value::as_str) {
            icons.insert(icon.to_string());
        }
    }
    icons
}

fn expected_primitives(repo: &Path) -> Result<BTreeMap<String, String>> {
    let mut expected = BTreeMap::new();
    for path in direct_child_skill_files(&repo.join("skills"))? {
        let name = path
            .parent()
            .and_then(|path| path.file_name())
            .and_then(|name| name.to_str())
            .context("skill path missing name")?;
        expected.insert(
            format!("skill:{name}"),
            path.strip_prefix(repo)?
                .to_string_lossy()
                .replace('\\', "/"),
        );
    }
    let agents = repo.join("agents");
    if agents.exists() {
        for entry in fs::read_dir(agents)? {
            let path = entry?.path();
            if path.extension().and_then(|value| value.to_str()) == Some("md") {
                let name = path
                    .file_stem()
                    .and_then(|name| name.to_str())
                    .unwrap_or("");
                expected.insert(
                    format!("agent:{name}"),
                    path.strip_prefix(repo)?
                        .to_string_lossy()
                        .replace('\\', "/"),
                );
            }
        }
    }
    Ok(expected)
}

fn direct_child_skill_files(root: &Path) -> Result<Vec<PathBuf>> {
    let mut paths = Vec::new();
    if !root.exists() {
        return Ok(paths);
    }
    for entry in fs::read_dir(root)? {
        let path = entry?.path();
        if path.is_dir() {
            let skill = path.join("SKILL.md");
            if skill.exists() {
                paths.push(skill);
            }
        }
    }
    paths.sort();
    Ok(paths)
}

fn compare_dirs(expected: &Path, actual: &Path) -> Result<Vec<String>> {
    let mut issues = Vec::new();
    compare_dirs_inner(expected, actual, &mut issues)?;
    Ok(issues)
}

fn compare_dirs_inner(expected: &Path, actual: &Path, issues: &mut Vec<String>) -> Result<()> {
    let expected_names = child_names(expected)?;
    let actual_names = child_names(actual)?;
    for name in expected_names.difference(&actual_names) {
        issues.push(format!(
            "missing generated path: {}",
            actual.join(name).display()
        ));
    }
    for name in actual_names.difference(&expected_names) {
        issues.push(format!(
            "unexpected generated path: {}",
            actual.join(name).display()
        ));
    }
    for name in expected_names.intersection(&actual_names) {
        let left = expected.join(name);
        let right = actual.join(name);
        if left.is_dir() && right.is_dir() {
            compare_dirs_inner(&left, &right, issues)?;
        } else if left.is_file() && right.is_file() {
            if fs::read(&left)? != fs::read(&right)? {
                issues.push(format!("stale generated path: {}", right.display()));
            }
        } else {
            issues.push(format!("stale generated path: {}", right.display()));
        }
    }
    Ok(())
}

fn child_names(path: &Path) -> Result<BTreeSet<String>> {
    let mut names = BTreeSet::new();
    if !path.exists() {
        return Ok(names);
    }
    for entry in fs::read_dir(path)? {
        names.insert(entry?.file_name().to_string_lossy().to_string());
    }
    Ok(names)
}

fn page_metadata(path: &Path) -> Result<(Option<String>, Option<String>)> {
    let text = fs::read_to_string(path)?;
    let primitive = Regex::new(r#"<meta name="harness-kit-primitive" content="([^"]+)">"#)?
        .captures(&text)
        .and_then(|captures| captures.get(1).map(|value| value.as_str().to_string()));
    let source = Regex::new(r#"<meta name="harness-kit-source" content="([^"]+)">"#)?
        .captures(&text)
        .and_then(|captures| captures.get(1).map(|value| value.as_str().to_string()));
    Ok((primitive, source))
}

fn html_img_srcs(text: &str) -> Vec<(String, String)> {
    let comments = Regex::new(r"(?s)<!--.*?-->").expect("valid regex");
    let text = comments.replace_all(text, "");
    let tag_regex = Regex::new(r"(?i)<img\b[^>]*>").expect("valid regex");
    let src_regex = Regex::new(r#"(?i)\bsrc\s*=\s*["']([^"']+)["']"#).expect("valid regex");
    let alt_regex = Regex::new(r#"(?i)\balt\s*=\s*["']([^"']*)["']"#).expect("valid regex");
    tag_regex
        .find_iter(&text)
        .filter_map(|tag| {
            let tag = tag.as_str();
            let src = src_regex
                .captures(tag)
                .and_then(|captures| captures.get(1).map(|value| value.as_str().to_string()))?;
            let alt = alt_regex
                .captures(tag)
                .and_then(|captures| captures.get(1).map(|value| value.as_str().to_string()))
                .unwrap_or_default();
            Some((src, alt))
        })
        .collect()
}

fn path_between_pages(page: &str, target: &str) -> String {
    let page_dir = Path::new(page).parent().unwrap_or_else(|| Path::new(""));
    if page_dir.as_os_str().is_empty() {
        return target.to_string();
    }
    let depth = page_dir.components().count();
    std::iter::repeat_n("..", depth)
        .chain(std::iter::once(target))
        .collect::<Vec<_>>()
        .join("/")
}

fn slug(value: &str) -> String {
    Regex::new(r"[^a-z0-9-]+")
        .expect("valid regex")
        .replace_all(&value.to_ascii_lowercase(), "-")
        .trim_matches('-')
        .to_string()
}

fn mutate_site_expect_failure(
    repo: &Path,
    label: &str,
    mutate: impl FnOnce(&Path) -> Result<()>,
) -> Result<()> {
    let temp = tempfile::tempdir().context("failed to create temporary directory")?;
    let base = temp.path().join("site");
    copy_dir(&repo.join("docs/site"), &base)?;
    mutate(&base)?;
    match validate_site(&CheckOptions {
        repo_root: repo.to_path_buf(),
        site: base,
        compare_to_rebuild: false,
    }) {
        Ok(()) => bail!("self-test did not fail for {label}"),
        Err(_) => Ok(()),
    }
}

fn expect_copy_failure(
    repo: &Path,
    label: &str,
    mutate: impl FnOnce(&mut Value) -> Result<()>,
) -> Result<()> {
    let mut copy: Value = serde_json::from_str(&fs::read_to_string(copy_source(repo))?)?;
    mutate(&mut copy)?;
    match image_declarations(repo, &copy) {
        Ok(_) => bail!("self-test did not fail for {label}"),
        Err(_) => Ok(()),
    }
}

fn copy_repo_for_self_test(source: &Path, destination: &Path) -> Result<()> {
    copy_dir_filtered(source, destination, &|path| {
        path.file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| {
                matches!(
                    name,
                    ".agents"
                        | ".antigravitycli"
                        | ".claude"
                        | ".codex"
                        | ".git"
                        | ".pi"
                        | "__pycache__"
                        | ".venv"
                        | "target"
                )
            })
            || path.ends_with("skills/.external")
    })
}

fn copy_dir(source: &Path, destination: &Path) -> Result<()> {
    copy_dir_filtered(source, destination, &|_| false)
}

fn copy_dir_filtered(
    source: &Path,
    destination: &Path,
    skip: &impl Fn(&Path) -> bool,
) -> Result<()> {
    if skip(source) {
        return Ok(());
    }
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let source_path = entry?.path();
        if skip(&source_path) {
            continue;
        }
        let destination_path = destination.join(
            source_path
                .file_name()
                .context("source path missing file name")?,
        );
        if source_path.is_dir() {
            copy_dir_filtered(&source_path, &destination_path, skip)?;
        } else {
            fs::copy(&source_path, destination_path)?;
        }
    }
    Ok(())
}

fn run_checked(command: &mut Command, label: &str) -> Result<()> {
    let output = command
        .output()
        .with_context(|| format!("failed to run {label}"))?;
    if !output.status.success() {
        bail!(
            "{label} failed: {}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(())
}

fn private_patterns() -> Result<Vec<Regex>> {
    Ok(vec![
        Regex::new(r"/Users/[A-Za-z0-9_-]+/")?,
        Regex::new("(?i)\\bdaybook\\b")?,
        Regex::new("(?i)provider-lanes/")?,
    ])
}

fn all_files(root: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    if !root.exists() {
        return Ok(files);
    }
    collect_files(root, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    for entry in fs::read_dir(root)? {
        let path = entry?.path();
        if path.is_dir() {
            collect_files(&path, files)?;
        } else if path.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

fn glob_html(root: &Path) -> Result<Vec<PathBuf>> {
    Ok(all_files(root)?
        .into_iter()
        .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("html"))
        .collect())
}

fn direct_html_files(root: &Path) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    if !root.exists() {
        return Ok(files);
    }
    for entry in fs::read_dir(root)? {
        let path = entry?.path();
        if path.is_file() && path.extension().and_then(|value| value.to_str()) == Some("html") {
            files.push(path);
        }
    }
    files.sort();
    Ok(files)
}

fn array<'a>(value: &'a Value, key: &str) -> &'a Vec<Value> {
    static EMPTY: std::sync::OnceLock<Vec<Value>> = std::sync::OnceLock::new();
    value
        .get(key)
        .and_then(Value::as_array)
        .unwrap_or_else(|| EMPTY.get_or_init(Vec::new))
}

fn array_mut<'a>(value: &'a mut Value, key: &str) -> Result<&'a mut Vec<Value>> {
    value
        .get_mut(key)
        .and_then(Value::as_array_mut)
        .with_context(|| format!("{key} must be array"))
}

fn string_field(value: &Value, key: &str, source: &Path) -> Result<String> {
    value
        .get(key)
        .and_then(Value::as_str)
        .map(str::to_string)
        .with_context(|| format!("{}: {key} must be string", source.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_matches_docs_builder_contract() {
        assert_eq!(slug("Review, QA + Ship!"), "review-qa-ship");
    }

    #[test]
    fn page_relative_image_path_matches_python_contract() {
        assert_eq!(
            path_between_pages("workflows/ship.html", "assets/images/ship.svg"),
            "../assets/images/ship.svg"
        );
        assert_eq!(
            path_between_pages("index.html", "assets/images/home.svg"),
            "assets/images/home.svg"
        );
    }

    #[test]
    fn html_img_srcs_ignores_comments_and_keeps_missing_alt_empty() {
        let found = html_img_srcs(
            r#"<!-- <img src="ignored.svg" alt="Ignored"> --><img alt="A" src="../a.svg"><img src='b.svg'>"#,
        );

        assert_eq!(
            found,
            vec![
                ("../a.svg".to_string(), "A".to_string()),
                ("b.svg".to_string(), String::new()),
            ]
        );
    }

    #[test]
    fn compare_dirs_reports_missing_unexpected_and_stale_paths() {
        let temp = tempfile::tempdir().unwrap();
        let expected = temp.path().join("expected");
        let actual = temp.path().join("actual");
        fs::create_dir_all(&expected).unwrap();
        fs::create_dir_all(&actual).unwrap();
        fs::write(expected.join("missing.txt"), "left").unwrap();
        fs::write(expected.join("stale.txt"), "left").unwrap();
        fs::write(actual.join("stale.txt"), "right").unwrap();
        fs::write(actual.join("extra.txt"), "right").unwrap();

        let issues = compare_dirs(&expected, &actual).unwrap();

        assert!(
            issues
                .iter()
                .any(|issue| issue.contains("missing generated path"))
        );
        assert!(
            issues
                .iter()
                .any(|issue| issue.contains("unexpected generated path"))
        );
        assert!(
            issues
                .iter()
                .any(|issue| issue.contains("stale generated path"))
        );
    }
}
