use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};
use pulldown_cmark::{Options as MarkdownOptions, Parser, html};

pub struct RenderOptions {
    pub input: PathBuf,
    pub output: Option<PathBuf>,
    pub open: bool,
}

pub struct RenderReport {
    pub output: PathBuf,
    pub opened: bool,
}

pub fn render(options: &RenderOptions) -> Result<RenderReport> {
    let input = absolute_path(&options.input)?;
    let markdown = fs::read_to_string(&input)
        .with_context(|| format!("failed to read {}", input.display()))?;
    let title = title_from_markdown(&markdown).unwrap_or_else(|| {
        input
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned()
    });
    let output = match &options.output {
        Some(output) => absolute_path(output)?,
        None => input.with_extension("html"),
    };
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(&output, render_html(&markdown, &title))
        .with_context(|| format!("failed to write {}", output.display()))?;
    if options.open {
        open_path(&output)?;
    }
    Ok(RenderReport {
        output,
        opened: options.open,
    })
}

fn absolute_path(path: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(std::env::current_dir()?.join(path))
    }
}

fn open_path(path: &Path) -> Result<()> {
    #[cfg(target_os = "macos")]
    let mut command = {
        let mut command = Command::new("open");
        command.arg(path);
        command
    };

    #[cfg(all(unix, not(target_os = "macos")))]
    let mut command = {
        let mut command = Command::new("xdg-open");
        command.arg(path);
        command
    };

    #[cfg(windows)]
    let mut command = {
        let mut command = Command::new("cmd");
        command.args(["/C", "start", ""]);
        command.arg(path);
        command
    };

    let status = command
        .status()
        .with_context(|| format!("failed to open {}", path.display()))?;
    anyhow::ensure!(
        status.success(),
        "open command failed for {}",
        path.display()
    );
    Ok(())
}

fn title_from_markdown(markdown: &str) -> Option<String> {
    markdown.lines().find_map(|line| {
        let title = line.strip_prefix("# ")?;
        let title = title.trim();
        (!title.is_empty()).then(|| title.to_string())
    })
}

fn render_html(markdown: &str, title: &str) -> String {
    let body = render_markdown(markdown);
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
:root {{ color-scheme: light dark; --bg: #f7f7f5; --fg: #151515; --muted: #5f625f; --line: #d8d8d2; --panel: #ffffff; --code: #eeeeea; }}
@media (prefers-color-scheme: dark) {{ :root {{ --bg: #151615; --fg: #f4f4ef; --muted: #b5b8b1; --line: #3a3d38; --panel: #1f211f; --code: #2b2d2a; }} }}
* {{ box-sizing: border-box; }}
body {{ margin: 0; background: var(--bg); color: var(--fg); font: 16px/1.55 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
main {{ max-width: 920px; margin: 0 auto; padding: 40px 24px 72px; }}
header {{ border-bottom: 1px solid var(--line); margin-bottom: 28px; padding-bottom: 18px; }}
.eyebrow {{ color: var(--muted); font-size: 13px; margin: 0 0 6px; text-transform: uppercase; letter-spacing: .08em; }}
h1 {{ font-size: 34px; line-height: 1.15; margin: 0 0 18px; }}
h2 {{ font-size: 22px; line-height: 1.25; margin: 34px 0 10px; border-top: 1px solid var(--line); padding-top: 22px; }}
h3 {{ font-size: 18px; margin: 24px 0 8px; }}
p, ul, ol, pre {{ margin: 0 0 14px; }}
ul, ol {{ padding-left: 28px; }}
li {{ margin: 5px 0; }}
code {{ background: var(--code); border-radius: 4px; padding: 1px 4px; }}
pre {{ background: var(--panel); border: 1px solid var(--line); border-radius: 8px; overflow: auto; padding: 14px 16px; }}
pre code {{ background: transparent; padding: 0; }}
blockquote {{ border-left: 4px solid var(--line); color: var(--muted); margin: 0 0 14px; padding-left: 14px; }}
.source {{ color: var(--muted); font-size: 13px; margin-top: 28px; }}
</style>
</head>
<body>
<main>
<header><p class="eyebrow">Harness Kit plan review</p><h1>{title}</h1></header>
{body}
<p class="source">Generated by <code>harness-kit-checks shape-render</code>. Markdown remains authoritative.</p>
</main>
</body>
</html>
"#,
        title = escape_html(title),
        body = body
    )
}

fn render_markdown(markdown: &str) -> String {
    let mut options = MarkdownOptions::empty();
    options.insert(MarkdownOptions::ENABLE_TABLES);
    options.insert(MarkdownOptions::ENABLE_FOOTNOTES);
    options.insert(MarkdownOptions::ENABLE_STRIKETHROUGH);
    options.insert(MarkdownOptions::ENABLE_TASKLISTS);
    let parser = Parser::new_ext(markdown, options);
    let mut rendered = String::new();
    html::push_html(&mut rendered, parser);
    rendered
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_review_html_with_headings_lists_and_code() {
        let html = render_html(
            "# Context Packet: Demo\n\n## Goal\nShip `x`.\n\n- Read files\n- Open review\n\n```sh\ncargo test\n```",
            "Context Packet: Demo",
        );
        assert!(html.contains("Harness Kit plan review"));
        assert!(html.contains("<h2>Goal</h2>"));
        assert!(html.contains("<code>x</code>"));
        assert!(html.contains("<li>Open review</li>"));
        assert!(html.contains("cargo test"));
    }

    #[test]
    fn defaults_output_next_to_input() {
        let temp = tempfile::tempdir().unwrap();
        let packet = temp.path().join("packet.md");
        fs::write(&packet, "# Packet\n\n## Goal\nReview me.").unwrap();
        let report = render(&RenderOptions {
            input: packet.clone(),
            output: None,
            open: false,
        })
        .unwrap();
        assert_eq!(report.output, packet.with_extension("html"));
        assert!(
            fs::read_to_string(report.output)
                .unwrap()
                .contains("Review me.")
        );
    }
}
