#!/usr/bin/env python3
"""Build Spellbook's generated static documentation companion."""

from __future__ import annotations

import argparse
import html
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED = "Generated by scripts/build-docs-site.py; do not edit manually."
ROOT = Path(__file__).resolve().parents[1]
COPY_SOURCE = ROOT / "docs/copy/site.json"


@dataclass(frozen=True)
class Primitive:
    kind: str
    name: str
    description: str
    source: str
    page: str
    role: str

    @property
    def ident(self) -> str:
        return f"{self.kind}:{self.name}"


WORKFLOW_ROLES = {
    "shape": "Plan",
    "implement": "Build",
    "deliver": "Orchestrate",
    "code-review": "Review",
    "ci": "Verify",
    "qa": "Verify",
    "refactor": "Improve",
    "ship": "Ship",
    "yeet": "Ship",
    "flywheel": "Operate",
    "monitor": "Operate",
    "reflect": "Learn",
    "harness": "Maintain",
    "research": "Explore",
    "groom": "Plan",
    "diagnose": "Repair",
}


GATE_DESCRIPTIONS = {
    "check-agent-roster": "Validates provider roster schema, receipt fixtures, delegation floors, and source-repo bridge hygiene.",
    "check-deliver-composition": "Ensures /deliver composes phase skills instead of inlining CI, QA, review, or claims internals.",
    "check-docs-site": "Rebuilds the static docs companion and fails on stale pages, missing primitives, broken workflow pages, or invalid icon/copy references.",
    "check-exclusions": "Blocks code-suppression comments, broad type escapes, and skipped tests.",
    "check-frontmatter": "Validates skill frontmatter fields and size limits.",
    "check-harness-install-paths": "Guards global, cross-harness install wording for /seed and /tailor.",
    "check-index-drift": "Regenerates index.yaml and fails if the committed catalog is stale.",
    "check-no-claims": "Prevents removed claim-coordination primitives from returning under skills/.",
    "check-portable-paths": "Rejects hardcoded user home paths outside explicitly allowed harness files.",
    "check-skill-evals": "Validates skill eval suites have README, cases, and graders.",
    "check-vendored-copies": "Ensures vendored repo-local harness copies match canonical sources.",
    "lint-python": "Compiles Python scripts outside ci/ to catch syntax errors.",
    "lint-shell": "Runs shellcheck on shell scripts outside ci/.",
    "lint-yaml": "Parses top-level YAML files.",
    "test-bun": "Runs the TypeScript test suite for the research skill.",
}


ICON_PATHS = {
    "build": '<path d="M14 4 20 10"/><path d="M16 2l6 6-9.5 9.5a3 3 0 0 1-4.2 0l-1.8-1.8a3 3 0 0 1 0-4.2L16 2Z"/><path d="M5 19l-2 2"/>',
    "catalog": '<rect x="4" y="4" width="6" height="6" rx="1.5"/><rect x="14" y="4" width="6" height="6" rx="1.5"/><rect x="4" y="14" width="6" height="6" rx="1.5"/><rect x="14" y="14" width="6" height="6" rx="1.5"/>',
    "learn": '<path d="M4 7a8 8 0 0 1 13.7-3.2"/><path d="M18 4v5h-5"/><path d="M20 17a8 8 0 0 1-13.7 3.2"/><path d="M6 20v-5h5"/>',
    "operate": '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3"/><path d="M12 19v3"/><path d="M2 12h3"/><path d="M19 12h3"/>',
    "plan": '<path d="M12 3 4 20l8-4 8 4-8-17Z"/><path d="M12 8v8"/>',
    "repair": '<path d="M12 3 5 6v5.5c0 4.5 2.9 8.3 7 9.5 4.1-1.2 7-5 7-9.5V6l-7-3Z"/><path d="m8.8 12.2 2.1 2.1 4.5-4.6"/>',
    "review": '<path d="M2.5 12s3.5-6.5 9.5-6.5 9.5 6.5 9.5 6.5-3.5 6.5-9.5 6.5S2.5 12 2.5 12Z"/><circle cx="12" cy="12" r="3"/>',
    "ship": '<path d="M4 12h14"/><path d="m13 7 5 5-5 5"/><path d="M4 5h5"/><path d="M4 19h5"/>',
    "specialist": '<circle cx="12" cy="8" r="3.5"/><path d="M5 20a7 7 0 0 1 14 0"/><path d="M19 5v4"/><path d="M17 7h4"/>',
    "verify": '<circle cx="12" cy="12" r="8"/><path d="m8.5 12.5 2.4 2.4 4.8-5.2"/>',
}


def load_copy() -> dict[str, Any]:
    try:
        data = json.loads(COPY_SOURCE.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"{COPY_SOURCE.relative_to(ROOT)} is missing") from exc
    require(data, "home", dict)
    require(data, "concepts", dict)
    require(data, "governance", dict)
    require(data, "workflows", list)
    require(data, "role_icons", dict)
    validate_icon_names(data)
    return data


def require(data: dict[str, Any], key: str, expected_type: type) -> Any:
    value = data.get(key)
    if not isinstance(value, expected_type):
        raise SystemExit(f"{COPY_SOURCE.relative_to(ROOT)}: {key} must be {expected_type.__name__}")
    return value


def validate_icon_names(data: dict[str, Any]) -> None:
    used: set[str] = set()
    for card_data in data.get("home", {}).get("start_cards", []):
        used.add(str(card_data.get("icon", "")))
    for concept in data.get("concepts", {}).get("items", []):
        if len(concept) >= 3:
            used.add(str(concept[2]))
    for workflow in data.get("workflows", []):
        used.add(str(workflow.get("icon", "")))
    for card_data in data.get("governance", {}).get("cards", []):
        if len(card_data) >= 3:
            used.add(str(card_data[2]))
    used.update(str(value) for value in data.get("role_icons", {}).values())
    missing = sorted(name for name in used if name and name not in ICON_PATHS)
    if missing:
        raise SystemExit(f"{COPY_SOURCE.relative_to(ROOT)} references unknown icon(s): {', '.join(missing)}")


COPY = load_copy()


def workflows() -> list[dict[str, str]]:
    return [dict(item) for item in COPY["workflows"]]


def role_icon(role: str) -> str:
    icons = COPY["role_icons"]
    return str(icons.get(role, "catalog"))


def icon_svg(name: str, current: str) -> str:
    if name not in ICON_PATHS:
        raise SystemExit(f"unknown icon: {name}")
    href = f"{rel(current, 'assets/icons.svg')}#icon-{name}"
    return f'<svg class="icon" aria-hidden="true"><use href="{href}"></use></svg>'


def render_icons() -> str:
    symbols = []
    for name, path in sorted(ICON_PATHS.items()):
        symbols.append(f'<symbol id="icon-{name}" viewBox="0 0 24 24">{path}</symbol>')
    return (
        f"<!-- {GENERATED} -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" fill="none" '
        'stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">\n'
        + "\n".join(symbols)
        + "\n</svg>\n"
    )


def slug(value: str) -> str:
    text = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    return text or "item"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = read(path)
    if not text.startswith("---\n"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    lines = parts[1].splitlines()
    data: dict[str, str] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line or line.startswith(" "):
            index += 1
            continue
        if ":" not in line:
            index += 1
            continue
        key, raw_value = line.split(":", 1)
        value = raw_value.strip()
        if value == "|":
            collected: list[str] = []
            index += 1
            while index < len(lines) and lines[index].startswith("  "):
                collected.append(lines[index].strip())
                index += 1
            data[key.strip()] = " ".join(collected).strip()
            continue
        data[key.strip()] = value.strip("\"'")
        index += 1
    return data


def first_heading(path: Path) -> str:
    for line in read(path).splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def primitive_description(path: Path) -> str:
    frontmatter = parse_frontmatter(path)
    description = frontmatter.get("description", "").strip()
    if description:
        return re.sub(r"\s+", " ", description)
    return first_heading(path)


def collect_primitives() -> list[Primitive]:
    primitives: list[Primitive] = []
    for skill_md in sorted((ROOT / "skills").glob("*/SKILL.md")):
        name = skill_md.parent.name
        source = skill_md.relative_to(ROOT).as_posix()
        primitives.append(
            Primitive(
                kind="skill",
                name=name,
                description=primitive_description(skill_md),
                source=source,
                page=f"reference/skills/{slug(name)}.html",
                role=WORKFLOW_ROLES.get(name, "Support"),
            )
        )
    for agent_md in sorted((ROOT / "agents").glob("*.md")):
        name = agent_md.stem
        source = agent_md.relative_to(ROOT).as_posix()
        primitives.append(
            Primitive(
                kind="agent",
                name=name,
                description=primitive_description(agent_md),
                source=source,
                page=f"reference/agents/{slug(name)}.html",
                role="Specialist",
            )
        )
    return primitives


def collect_gates() -> list[str]:
    text = read(ROOT / "ci/src/spellbook_ci/main.py")
    return sorted(set(re.findall(r'run_gate,\s+"([^"]+)"', text)))


def collect_backlog() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    for path in sorted((ROOT / "backlog.d").glob("[0-9]*.md")):
        text = read(path)
        title = text.splitlines()[0].lstrip("# ").strip() if text else path.stem
        items.append({"title": title, "source": path.relative_to(ROOT).as_posix()})
    return items


def rel(current: str, target: str) -> str:
    current_parent = Path(current).parent
    if current_parent == Path("."):
        return Path(target).relative_to(".").as_posix()
    return "../" * len(current_parent.parts) + target


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def script_json(value: str) -> str:
    return value.replace("<", "\\u003c").replace("&", "\\u0026")


def trigger_for(primitive: Primitive) -> str:
    return f"/{primitive.name}" if primitive.kind == "skill" else primitive.name


def page_excerpt(source: str) -> str:
    path = ROOT / source
    lines = []
    in_frontmatter = False
    started = False
    for raw in read(path).splitlines():
        line = raw.rstrip()
        if line == "---":
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter:
            continue
        if line.startswith("# ") and not started:
            started = True
            continue
        if not line.strip() and not lines:
            continue
        lines.append(line)
        if len("\n".join(lines)) > 1800:
            break
    excerpt = "\n".join(lines).strip()
    return excerpt + ("\n..." if len(excerpt) > 1750 else "")


def render_excerpt(source: str) -> str:
    excerpt = page_excerpt(source)
    if not excerpt:
        return ""
    return f'<pre class="source-excerpt"><code>{esc(excerpt)}</code></pre>'


def page_shell(title: str, current: str, body: str) -> str:
    css = rel(current, "assets/site.css")
    home = rel(current, "index.html")
    concepts = rel(current, "concepts.html")
    workflows_href = rel(current, "workflows.html")
    governance = rel(current, "governance.html")
    reference = rel(current, "reference/index.html")
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="{GENERATED}">
  <title>{esc(title)} | Spellbook Docs</title>
  <link rel="stylesheet" href="{css}">
</head>
<body>
  <header class="topbar">
    <a class="brand" href="{home}">Spellbook</a>
    <nav aria-label="Primary">
      <a href="{concepts}">Concepts</a>
      <a href="{workflows_href}">Workflows</a>
      <a href="{governance}">Governance</a>
      <a href="{reference}">Reference</a>
    </nav>
  </header>
  <main>
{body}
  </main>
</body>
</html>
"""


def source_link(source: str, current: str) -> str:
    _ = current
    return f'<a href="https://github.com/misty-step/spellbook/blob/master/{source}">{esc(source)}</a>'


def card(title: str, text: str, href: str = "", icon: str = "", current: str = "index.html") -> str:
    icon_markup = icon_svg(icon, current) if icon else ""
    link = f'<a class="card-link" href="{href}">Open</a>' if href else ""
    return f'<article class="card">{icon_markup}<h3>{esc(title)}</h3><p>{esc(text)}</p>{link}</article>'


def render_quickstart(current: str, quickstart: dict[str, object]) -> str:
    steps = []
    for index, step in enumerate(quickstart["steps"], 1):
        steps.append(
            f'<article class="quickstep"><span>{index}</span><h3>{esc(step["label"])}</h3>'
            f'<code>{esc(step["command"])}</code><p>{esc(step["detail"])}</p></article>'
        )
    return f'''
    <section class="quickstart">
      <div>
        <p class="eyebrow">Quickstart</p>
        <h2>{esc(quickstart["title"])}</h2>
        <p>{esc(quickstart["lede"])}</p>
      </div>
      <div class="quicksteps">{''.join(steps)}</div>
      <p class="source">Sources: {source_link('bootstrap.sh', current)}, {source_link('skills/shape/SKILL.md', current)}, {source_link('skills/deliver/SKILL.md', current)}</p>
    </section>
'''


def render_task_finder(current: str, task_finder: dict[str, object]) -> str:
    items = []
    for item in task_finder["items"]:
        href = rel(current, item["href"]) if not str(item["href"]).startswith("http") else item["href"]
        items.append(
            f'<a class="task-card" href="{href}">{icon_svg(item["icon"], current)}'
            f'<span>{esc(item["use"])}</span><strong>{esc(item["task"])}</strong></a>'
        )
    return f'''
    <section>
      <p class="eyebrow">Chooser</p>
      <h2>{esc(task_finder["title"])}</h2>
      <p>{esc(task_finder["lede"])}</p>
      <div class="task-grid">{''.join(items)}</div>
    </section>
'''


def render_home(primitives: list[Primitive], backlog: list[dict[str, str]]) -> str:
    current = "index.html"
    copy = COPY["home"]
    start_cards = []
    for item in copy["start_cards"]:
        start_cards.append(card(item["title"], item["text"], item["href"], item["icon"], current))
    flow = "".join(f"<span>{esc(label)}</span>" for label in copy["flow"])
    body = f"""
    <section class="hero">
      <div class="hero-copy">
        <p class="eyebrow">{esc(copy['eyebrow'])}</p>
        <h1>{esc(copy['title'])}</h1>
        <p class="lede">{esc(copy['lede'])}</p>
        <p class="hero-links"><a href="concepts.html">Read the concepts</a><a href="reference/index.html">Browse the catalog</a></p>
        <div class="metrics">
          <span><strong>{len([p for p in primitives if p.kind == 'skill'])}</strong> skills</span>
          <span><strong>{len([p for p in primitives if p.kind == 'agent'])}</strong> agents</span>
          <span><strong>{len(collect_gates())}</strong> CI gates</span>
        </div>
      </div>
      <aside class="hero-map" aria-label="Spellbook operating loop">
        <span>{icon_svg('plan', current)}Shape</span>
        <span>{icon_svg('operate', current)}Delegate</span>
        <span>{icon_svg('verify', current)}Verify</span>
        <span>{icon_svg('learn', current)}Improve</span>
      </aside>
    </section>
    <section class="band">
      <h2>{esc(copy['sixty_title'])}</h2>
      <p>{esc(copy['sixty_copy'])}</p>
      <div class="flow">{flow}</div>
    </section>
    {render_quickstart(current, copy['quickstart'])}
    {render_task_finder(current, copy['task_finder'])}
    <section>
      <h2>Start here</h2>
      <div class="grid three">
        {''.join(start_cards)}
      </div>
    </section>
    <section>
      <h2>{esc(copy['boundary_title'])}</h2>
      <p>{esc(copy['boundary_copy'])}</p>
      <p class="source">Source: {source_link('docs/positioning.md', current)}</p>
    </section>
    <section>
      <h2>{esc(copy['backlog_title'])}</h2>
      <p>{esc(copy['backlog_copy'])}</p>
      <ul class="compact">
        {''.join(f'<li><a href="https://github.com/misty-step/spellbook/blob/master/{esc(item["source"])}">{esc(item["title"])}</a> <span>{esc(item["source"])}</span></li>' for item in backlog[:6])}
      </ul>
    </section>
"""
    return page_shell("Start", current, body)


def render_concepts() -> str:
    current = "concepts.html"
    copy = COPY["concepts"]
    cards = "".join(card(title, text, icon=icon, current=current) for title, text, icon in copy["items"])
    body = f"""
    <section class="page-head">
      <p class="eyebrow">{esc(copy['eyebrow'])}</p>
      <h1>{esc(copy['title'])}</h1>
      <p class="lede">{esc(copy['lede'])}</p>
    </section>
    <section class="grid two">
      {cards}
    </section>
    <section class="checklist">
      <h2>What to verify</h2>
      <ul>
        <li>Every primitive points back to a source file in this repository.</li>
        <li>Every workflow names its expected evidence before it claims completion.</li>
        <li>Provider output is treated as evidence, not authority.</li>
      </ul>
      <p class="source">Sources: {source_link('agents', current)}, {source_link('skills', current)}, {source_link('harnesses/shared/AGENTS.md', current)}</p>
    </section>
"""
    return page_shell("Concepts", current, body)


def render_workflows() -> str:
    current = "workflows.html"
    items = []
    for workflow in workflows():
        href = rel(current, workflow_page(workflow))
        icon_markup = icon_svg(workflow["icon"], current)
        items.append(
            f'<article class="workflow">{icon_markup}<h2>{esc(workflow["title"])}</h2>'
            f'<p>{esc(workflow["summary"])}</p>'
            f'<p class="proof">Evidence: {esc(workflow["evidence"])}</p>'
            f'<a class="card-link" href="{href}">Open workflow</a></article>'
        )
    body = f"""
    <section class="page-head">
      <p class="eyebrow">Workflows</p>
      <h1>From zero to one, then into the operating loop.</h1>
      <p class="lede">These walkthroughs show how Spellbook turns human requests into governed, reviewable agent work.</p>
    </section>
    <section class="stack">
      {''.join(items)}
    </section>
    <section class="checklist">
      <h2>What to verify</h2>
      <ul>
        <li>The workflow has a named input, decision point, output, and evidence path.</li>
        <li>At least two roster providers were used for substantive work when available.</li>
        <li>The branch remains clean and the repo gate is green before closeout.</li>
      </ul>
      <p class="source">Sources: {source_link('skills/deliver/SKILL.md', current)}, {source_link('bootstrap.sh', current)}</p>
    </section>
"""
    return page_shell("Workflows", current, body)


def workflow_page(workflow: dict[str, str]) -> str:
    return f"workflows/{slug(workflow['title'])}.html"


def render_workflow_page(workflow: dict[str, str]) -> str:
    current = workflow_page(workflow)
    body = f"""
    <section class="page-head workflow-head">
      {icon_svg(workflow['icon'], current)}
      <p class="eyebrow">Workflow</p>
      <h1>{esc(workflow['title'])}</h1>
      <p class="lede">{esc(workflow['summary'])}</p>
      <p class="source">Source: {source_link(workflow['source'], current)}</p>
    </section>
    <section class="steps">
      <article><span>Input</span><p>{esc(workflow['input'])}</p></article>
      <article><span>Decision</span><p>{esc(workflow['decision'])}</p></article>
      <article><span>Evidence</span><p>{esc(workflow['evidence'])}</p></article>
      <article><span>Failure handling</span><p>{esc(workflow['failure'])}</p></article>
    </section>
    <section class="checklist">
      <h2>What to verify</h2>
      <ul>
        <li>The input exists in live repo or operator evidence, not memory.</li>
        <li>The decision is narrow enough to verify with an oracle.</li>
        <li>The evidence path is captured before closeout.</li>
      </ul>
    </section>
"""
    return page_shell(workflow["title"], current, body)


def render_governance() -> str:
    current = "governance.html"
    copy = COPY["governance"]
    cards = "".join(card(title, text, icon=icon, current=current) for title, text, icon in copy["cards"])
    body = f"""
    <section class="page-head">
      <p class="eyebrow">{esc(copy['eyebrow'])}</p>
      <h1>{esc(copy['title'])}</h1>
      <p class="lede">{esc(copy['lede'])}</p>
    </section>
    <section class="grid two">
      {cards}
    </section>
    <section class="checklist">
      <h2>What to verify</h2>
      <ul>
        <li>The workflow has an evaluation or oracle tied to the user-visible promise.</li>
        <li>Receipts show which providers ran and what the lead accepted or rejected.</li>
        <li>The docs avoid claims that Spellbook provides RBAC, spend controls, procurement workflows, or incident dashboards.</li>
      </ul>
      <p class="source">Sources: {source_link('.spellbook/agents.yaml', current)}, {source_link('docs/positioning.md', current)}</p>
    </section>
"""
    return page_shell("Governance", current, body)


def primitive_card(primitive: Primitive, current: str) -> str:
    href = rel(current, primitive.page)
    icon = icon_svg(role_icon(primitive.role), current)
    return (
        f'<article class="catalog-card" data-kind="{primitive.kind}" data-role="{esc(primitive.role)}">'
        f'{icon}<span>{esc(primitive.kind)}</span><h3>{esc(primitive.name)}</h3>'
        f'<code class="trigger">{esc(trigger_for(primitive))}</code>'
        f'<p>{esc(primitive.description)}</p><a href="{href}">Reference</a></article>'
    )


def render_reference(primitives: list[Primitive], gates: list[str]) -> str:
    current = "reference/index.html"
    manifest = json.dumps([primitive.__dict__ | {"id": primitive.ident} for primitive in primitives], sort_keys=True)
    body = f"""
    <section class="page-head">
      <p class="eyebrow">Reference</p>
      <h1>Generated catalog of local skills, agents, gates, and bootstrap behavior.</h1>
      <p class="lede">This section is rebuilt from source files so the public documentation cannot drift silently from the harness.</p>
    </section>
    <section class="controls" aria-label="Catalog filters">
      <input id="catalog-search" type="search" placeholder="Search {len([p for p in primitives if p.kind == 'skill'])} skills and {len([p for p in primitives if p.kind == 'agent'])} agents" aria-label="Search skills and agents">
      <select id="catalog-kind"><option value="">All primitives</option><option value="skill">Skills</option><option value="agent">Agents</option></select>
      <select id="catalog-role"><option value="">All roles</option></select>
    </section>
    <section id="catalog-grid" class="catalog-grid">
      {''.join(primitive_card(primitive, current) for primitive in primitives)}
    </section>
    <p id="catalog-empty" class="empty" hidden>No primitives match those filters.</p>
    <script id="catalog-data" type="application/json">{script_json(manifest)}</script>
    <script src="{rel(current, 'assets/catalog.js')}"></script>
    <section class="grid three">
      {card('CI gate map', f'{len(gates)} gates enforced by Dagger.', rel(current, 'reference/gates.html'), 'verify', current)}
      {card('Bootstrap behavior', 'How Spellbook installs skills, agents, and roster config.', rel(current, 'reference/bootstrap.html'), 'build', current)}
      {card('Agent-readable manifest', 'Compact generated context for coding agents.', rel(current, 'llms.txt'), 'catalog', current)}
    </section>
"""
    return page_shell("Reference", current, body)


def render_primitive(primitive: Primitive) -> str:
    current = primitive.page
    body = f"""
    <section class="page-head primitive-head" data-primitive-id="{primitive.ident}">
      {icon_svg(role_icon(primitive.role), current)}
      <p class="eyebrow">{esc(primitive.kind)}</p>
      <h1>{esc(primitive.name)}</h1>
      <p class="lede">{esc(primitive.description)}</p>
      <p><code class="trigger large">{esc(trigger_for(primitive))}</code></p>
      <p class="source">Source: {source_link(primitive.source, current)}</p>
    </section>
    <section class="grid two">
      {card('What it does', primitive.description, icon='catalog', current=current)}
      {card('Workflow role', f'{primitive.role} primitive in the Spellbook operating loop.', icon=role_icon(primitive.role), current=current)}
    </section>
    <section>
      <h2>Source contract preview</h2>
      <p>This generated excerpt gives readers the beginning of the live primitive contract before they jump to GitHub.</p>
      {render_excerpt(primitive.source)}
    </section>
    <section class="checklist">
      <h2>What to verify</h2>
      <ul>
        <li>The source file exists and carries valid frontmatter.</li>
        <li>The primitive has one generated reference page.</li>
        <li>Claims about behavior can be traced back to the linked source.</li>
      </ul>
    </section>
"""
    return page_shell(f"{primitive.kind.title()}: {primitive.name}", current, body).replace(
        "<meta name=\"generator\"",
        f"<meta name=\"spellbook-primitive\" content=\"{primitive.ident}\">\n  <meta name=\"spellbook-source\" content=\"{primitive.source}\">\n  <meta name=\"generator\"",
    )


def render_gates(gates: list[str]) -> str:
    current = "reference/gates.html"
    body = f"""
    <section class="page-head">
      {icon_svg('verify', current)}
      <p class="eyebrow">Reference</p>
      <h1>CI gate map</h1>
      <p class="lede">The repo's load-bearing verification is Dagger. These gates are extracted from ci/src/spellbook_ci/main.py.</p>
    </section>
    <section class="grid three">
      {''.join(card(gate, GATE_DESCRIPTIONS.get(gate, 'Runs as part of dagger call check --source=.'), icon='verify', current=current) for gate in gates)}
    </section>
    <p class="source">Source: {source_link('ci/src/spellbook_ci/main.py', current)}</p>
"""
    return page_shell("CI Gates", current, body)


def render_bootstrap() -> str:
    current = "reference/bootstrap.html"
    body = f"""
    <section class="page-head">
      {icon_svg('build', current)}
      <p class="eyebrow">Reference</p>
      <h1>Bootstrap behavior</h1>
      <p class="lede">bootstrap.sh installs the system-wide harness links and provider roster. Consumer repos can then use Spellbook without vendoring source-repo skill bridges.</p>
    </section>
    <section class="quickstart">
      <div>
        <p class="eyebrow">First install</p>
        <h2>Run bootstrap from a stable checkout</h2>
        <p>Use the local checkout when you have it. The remote one-liner exists for fresh machines.</p>
      </div>
      <div class="quicksteps">
        <article class="quickstep"><span>1</span><h3>Local checkout</h3><code>./bootstrap.sh</code><p>Links first-party skills, agents, shared doctrine, and provider roster files.</p></article>
        <article class="quickstep"><span>2</span><h3>Fresh machine</h3><code>curl -sL https://raw.githubusercontent.com/misty-step/spellbook/master/bootstrap.sh | bash</code><p>Downloads the bootstrap script and installs the global harness links.</p></article>
        <article class="quickstep"><span>3</span><h3>Verify</h3><code>ls ~/.codex/skills ~/.claude/skills ~/.pi/skills</code><p>At least one supported harness should show Spellbook skills after install.</p></article>
      </div>
    </section>
    <section class="grid two">
      {card('System install', 'Installs first-party skills and agents into supported local harnesses.', icon='build', current=current)}
      {card('Stable checkout', 'Prefers a stable checkout over temporary worktrees unless SPELLBOOK_DIR is set.', icon='operate', current=current)}
      {card('Roster config', 'Keeps external provider definitions available system-wide.', icon='catalog', current=current)}
      {card('Source cleanliness', 'Does not recreate source-repo .agents/.codex/.claude/.pi skill bridges.', icon='verify', current=current)}
    </section>
    <p class="source">Source: {source_link('bootstrap.sh', current)}</p>
"""
    return page_shell("Bootstrap", current, body)


def render_llms(primitives: list[Primitive], gates: list[str]) -> str:
    lines = [
        "# Spellbook generated docs context",
        "",
        GENERATED,
        "Copy source: docs/copy/site.json",
        "",
        "Spellbook is an operator-facing harness primitive library for AI-assisted software development.",
        "It is not an enterprise admin-control plane or procurement-ready client package.",
        "",
        "Core pages:",
        "- Start: docs/site/index.html",
        "- Concepts: docs/site/concepts.html",
        "- Workflows: docs/site/workflows.html",
        "- Governance: docs/site/governance.html",
        "- Reference: docs/site/reference/index.html",
        "",
        "Onboarding path:",
        "- Install: ./bootstrap.sh",
        "- First workflow: /shape -> /deliver -> /ci + /qa -> /reflect",
        "- Use the Start page chooser to map jobs to primitives.",
        "",
        "Primitives:",
    ]
    for primitive in primitives:
        lines.append(f"- {primitive.kind}:{primitive.name} | {primitive.source} | docs/site/{primitive.page}")
    lines.extend(["", "CI gates:"])
    lines.extend(f"- {gate}" for gate in gates)
    return "\n".join(lines) + "\n"


def render_manifest(primitives: list[Primitive], gates: list[str], backlog: list[dict[str, str]]) -> str:
    payload = {
        "generated_by": "scripts/build-docs-site.py",
        "copy_source": "docs/copy/site.json",
        "do_not_edit": True,
        "icons": sorted(ICON_PATHS),
        "primitives": [primitive.__dict__ | {"id": primitive.ident, "icon": role_icon(primitive.role)} for primitive in primitives],
        "onboarding": {"quickstart": COPY["home"]["quickstart"], "task_finder": COPY["home"]["task_finder"]},
        "workflows": workflows(),
        "gates": gates,
        "backlog": backlog,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


CSS = """
:root { color-scheme: light; --ink:#111827; --muted:#5b6575; --line:#d9dee8; --paper:#fbfcff; --panel:#ffffff; --accent:#246bfe; --accent2:#00a889; }
* { box-sizing: border-box; }
body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: var(--ink); background: var(--paper); line-height: 1.55; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.topbar { position: sticky; top: 0; z-index: 5; display:flex; align-items:center; justify-content:space-between; gap:24px; padding:16px clamp(20px, 5vw, 64px); border-bottom:1px solid rgba(17,24,39,.08); background:rgba(251,252,255,.92); backdrop-filter: blur(14px); }
.brand { display:inline-flex; align-items:center; gap:10px; font-weight: 800; letter-spacing: 0; color: var(--ink); }
.brand::before { content:""; width:18px; height:18px; border-radius:6px; background:linear-gradient(135deg, var(--accent), var(--accent2)); box-shadow:0 5px 18px rgba(36,107,254,.25); }
nav { display:flex; gap:18px; flex-wrap:wrap; font-size:14px; }
main { padding-bottom: 64px; }
section { max-width: 1120px; margin: 0 auto; padding: 42px clamp(20px, 5vw, 64px); }
.hero { display:grid; grid-template-columns:minmax(0, 1.35fr) minmax(280px, .65fr); gap:56px; align-items:center; padding-top: 74px; padding-bottom:54px; }
.hero-copy { min-width:0; }
.hero-map { border:1px solid var(--line); border-radius:8px; background:linear-gradient(180deg, #ffffff, #f7fbff); box-shadow:0 22px 50px rgba(17,24,39,.07); padding:18px; display:grid; gap:10px; }
.hero-map span { display:flex; align-items:center; gap:12px; padding:13px 14px; border:1px solid #e3e8f2; border-radius:8px; background:#fff; font-weight:800; color:var(--ink); }
.hero-map .icon { width:20px; height:20px; margin:0; color:var(--accent); }
.eyebrow { margin:0 0 12px; color:var(--accent2); font-size:13px; font-weight:800; text-transform:uppercase; letter-spacing:.08em; }
h1 { margin:0; max-width:820px; font-size: clamp(38px, 5vw, 64px); line-height:1.03; letter-spacing:0; }
.page-head h1 { font-size: clamp(36px, 5vw, 64px); }
h2 { margin:0 0 14px; font-size: clamp(24px, 3vw, 38px); line-height:1.1; letter-spacing:0; }
h3 { margin:0 0 8px; font-size:20px; line-height:1.2; }
.lede { max-width:760px; color:var(--muted); font-size:20px; }
.hero-links { display:flex; gap:18px; flex-wrap:wrap; margin:22px 0 0; font-weight:800; }
.hero-links a::after { content:" ->"; }
.icon { width:24px; height:24px; display:block; color:var(--accent); stroke:var(--accent); fill:none; margin-bottom:16px; }
.page-head > .icon { width:34px; height:34px; }
.metrics { display:flex; gap:10px; flex-wrap:wrap; margin-top:28px; }
.metrics span, .proof, .source { border:1px solid var(--line); background:var(--panel); border-radius:8px; padding:8px 12px; color:var(--muted); }
.metrics strong { color:var(--ink); }
.band { max-width:none; background:#eef5ff; border-block:1px solid #dce8ff; }
.band > * { max-width:1000px; margin-left:auto; margin-right:auto; }
.flow { display:grid; grid-template-columns: repeat(5, minmax(120px, 1fr)); gap:10px; margin-top:24px; }
.flow span { position:relative; padding:14px; background:var(--panel); border:1px solid #cbd8f6; border-radius:8px; text-align:center; font-weight:800; }
.flow span:not(:last-child)::after { content:""; position:absolute; top:50%; right:-10px; width:10px; border-top:2px solid #b8c8ec; transform:translateY(-50%); }
.quickstart { display:grid; grid-template-columns:minmax(240px, .7fr) minmax(0, 1.3fr); gap:24px; align-items:start; }
.quickstart > div:first-child p:not(.eyebrow) { color:var(--muted); }
.quicksteps { display:grid; gap:12px; }
.quickstep { border:1px solid var(--line); border-radius:8px; background:var(--panel); padding:18px; }
.quickstep span { display:inline-grid; place-items:center; width:28px; height:28px; border-radius:999px; background:#eef5ff; color:var(--accent); font-weight:800; margin-bottom:12px; }
.quickstep code { display:block; padding:10px 12px; border:1px solid #e3e8f2; border-radius:8px; background:#f8fafc; color:var(--ink); font-family:ui-monospace, SFMono-Regular, Menlo, monospace; font-size:13px; overflow-wrap:anywhere; }
.quickstep p { color:var(--muted); margin-bottom:0; }
.task-grid { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:14px; margin-top:18px; }
.task-card { display:grid; gap:8px; align-content:start; min-height:150px; border:1px solid var(--line); border-radius:8px; background:var(--panel); padding:18px; color:var(--ink); box-shadow:0 10px 28px rgba(17,24,39,.04); transition:border-color .15s ease, transform .15s ease, box-shadow .15s ease; }
.task-card:hover { text-decoration:none; border-color:#b8c8ec; transform:translateY(-1px); box-shadow:0 16px 34px rgba(17,24,39,.07); }
.task-card .icon { margin-bottom:2px; }
.task-card span { color:var(--accent); font-weight:800; font-family:ui-monospace, SFMono-Regular, Menlo, monospace; font-size:13px; }
.task-card strong { font-size:18px; line-height:1.25; }
.empty { max-width:1120px; margin:0 auto; padding:0 clamp(20px, 5vw, 64px) 28px; color:var(--muted); font-weight:700; }
.trigger { display:inline-block; width:max-content; max-width:100%; padding:5px 8px; border:1px solid #dce8ff; border-radius:6px; background:#f8fbff; color:var(--accent); font-family:ui-monospace, SFMono-Regular, Menlo, monospace; font-size:13px; font-weight:800; overflow-wrap:anywhere; }
.trigger.large { font-size:15px; padding:8px 10px; margin-top:10px; }
.source-excerpt { margin:18px 0 0; padding:18px; border:1px solid var(--line); border-radius:8px; background:#0f172a; color:#e5ecff; overflow:auto; white-space:pre-wrap; font-size:13px; line-height:1.55; }
.source-excerpt code { font-family:ui-monospace, SFMono-Regular, Menlo, monospace; }
.grid { display:grid; gap:16px; }
.grid.two { grid-template-columns: repeat(2, minmax(0, 1fr)); }
.grid.three { grid-template-columns: repeat(3, minmax(0, 1fr)); }
.card, .catalog-card, .workflow { background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:22px; box-shadow: 0 10px 28px rgba(17,24,39,.04); transition:border-color .15s ease, transform .15s ease, box-shadow .15s ease; }
.card:hover, .catalog-card:hover, .workflow:hover { border-color:#b8c8ec; transform:translateY(-1px); box-shadow:0 16px 34px rgba(17,24,39,.07); }
.card p, .catalog-card p, .workflow p { color:var(--muted); margin-bottom:0; }
.card-link, .catalog-card a { display:inline-block; margin-top:16px; font-weight:800; }
.stack { display:grid; gap:16px; }
.workflow { border-left:4px solid var(--accent); }
.workflow .icon, .catalog-card .icon { margin-bottom:14px; }
.steps { display:grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap:12px; }
.steps article { background:var(--panel); border:1px solid var(--line); border-radius:8px; padding:18px; }
.steps span { display:block; margin-bottom:8px; color:var(--accent2); font-size:12px; font-weight:800; text-transform:uppercase; letter-spacing:.08em; }
.proof { display:inline-block; margin-top:16px; }
.checklist { background:#f7f8fb; border-block:1px solid var(--line); max-width:none; }
.checklist > * { max-width:960px; margin-left:auto; margin-right:auto; }
.compact { padding-left:0; list-style:none; display:grid; gap:10px; }
.compact li { display:grid; grid-template-columns:minmax(0, 1fr) auto; align-items:center; gap:12px; padding:12px 0; border-bottom:1px solid var(--line); }
.compact a { color:var(--ink); font-weight:700; }
.compact span { color:var(--muted); font-family:ui-monospace, SFMono-Regular, Menlo, monospace; font-size:13px; overflow-wrap:anywhere; }
.source { display:inline-block; font-size:14px; }
.controls { display:flex; gap:12px; align-items:center; padding-top:0; }
input, select { min-height:42px; border:1px solid var(--line); border-radius:8px; padding:8px 12px; background:var(--panel); color:var(--ink); font:inherit; }
input { flex:1; min-width:220px; }
.catalog-grid { display:grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap:16px; padding-top:8px; }
.catalog-card span { display:inline-block; margin-bottom:12px; color:var(--accent2); font-size:12px; font-weight:800; text-transform:uppercase; letter-spacing:.08em; }
.primitive-head { border-bottom:1px solid var(--line); }
@media (max-width: 980px) { .hero, .quickstart { grid-template-columns:1fr; gap:28px; } .hero-map { grid-template-columns:repeat(2, minmax(0, 1fr)); } .task-grid { grid-template-columns:repeat(2, minmax(0, 1fr)); } }
@media (max-width: 820px) { .topbar { align-items:flex-start; flex-direction:column; } .flow, .grid.two, .grid.three, .catalog-grid, .steps, .task-grid { grid-template-columns:1fr; } .flow span:not(:last-child)::after { display:none; } h1 { font-size:42px; } .controls { align-items:stretch; flex-direction:column; } .compact li { align-items:flex-start; grid-template-columns:1fr; } }
@media (max-width: 520px) { section { padding-inline:20px; } .hero { padding-top:48px; } .hero-map { grid-template-columns:1fr; } .lede { font-size:18px; } }
""".strip() + "\n"


JS = """
(() => {
  const data = JSON.parse(document.getElementById("catalog-data").textContent);
  const cards = Array.from(document.querySelectorAll(".catalog-card"));
  const search = document.getElementById("catalog-search");
  const kind = document.getElementById("catalog-kind");
  const role = document.getElementById("catalog-role");
  const roles = [...new Set(data.map(item => item.role))].sort();
  for (const value of roles) {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = value;
    role.append(option);
  }
  const empty = document.getElementById("catalog-empty");
  function apply() {
    const q = search.value.trim().toLowerCase();
    let visibleCount = 0;
    for (const card of cards) {
      const text = card.textContent.toLowerCase();
      const visible = (!q || text.includes(q)) && (!kind.value || card.dataset.kind === kind.value) && (!role.value || card.dataset.role === role.value);
      card.hidden = !visible;
      if (visible) visibleCount += 1;
    }
    if (empty) empty.hidden = visibleCount !== 0;
  }
  search.addEventListener("input", apply);
  kind.addEventListener("change", apply);
  role.addEventListener("change", apply);
})();
""".strip() + "\n"


def write_file(output: Path, relative: str, content: str) -> None:
    path = output / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build(output: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)
    primitives = collect_primitives()
    gates = collect_gates()
    backlog = collect_backlog()
    write_file(output, "index.html", render_home(primitives, backlog))
    write_file(output, "concepts.html", render_concepts())
    write_file(output, "workflows.html", render_workflows())
    for workflow in workflows():
        write_file(output, workflow_page(workflow), render_workflow_page(workflow))
    write_file(output, "governance.html", render_governance())
    write_file(output, "reference/index.html", render_reference(primitives, gates))
    write_file(output, "reference/gates.html", render_gates(gates))
    write_file(output, "reference/bootstrap.html", render_bootstrap())
    for primitive in primitives:
        write_file(output, primitive.page, render_primitive(primitive))
    write_file(output, "manifest.json", render_manifest(primitives, gates, backlog))
    write_file(output, "llms.txt", render_llms(primitives, gates))
    write_file(output, ".nojekyll", "")
    write_file(output, "assets/site.css", f"/* {GENERATED} */\n{CSS}")
    write_file(output, "assets/catalog.js", f"// {GENERATED}\n{JS}")
    write_file(output, "assets/icons.svg", render_icons())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "docs/site")
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    build(output)
    print(f"Built {output.relative_to(ROOT) if output.is_relative_to(ROOT) else output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
