#!/usr/bin/env python3
"""Validate generated Harness Kit docs site output."""

from __future__ import annotations

import argparse
import filecmp
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "docs/site"
COPY_SOURCE = ROOT / "docs/copy/site.json"
GENERATED = "Generated by scripts/build-docs-site.py; do not edit manually."
PRIVATE_PATTERNS = [
    re.compile(r"/Users/[A-Za-z0-9_-]+/"),
    re.compile(r"\bdaybook\b", re.IGNORECASE),
    re.compile(r"provider-lanes/", re.IGNORECASE),
]


def load_copy() -> dict[str, object]:
    if not COPY_SOURCE.exists():
        fail(f"{COPY_SOURCE}: missing docs copy source")
    text = COPY_SOURCE.read_text(encoding="utf-8")
    for pattern in PRIVATE_PATTERNS:
        if pattern.search(text):
            fail(f"{COPY_SOURCE}: copy source contains private or local-only text matching {pattern.pattern}")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        fail(f"{COPY_SOURCE}: invalid JSON: {exc}")
    for key in ["home", "concepts", "governance", "workflows", "role_icons"]:
        if key not in data:
            fail(f"{COPY_SOURCE}: missing required key {key}")
    return data


def required_icons(copy: dict[str, object], manifest: dict[str, object]) -> set[str]:
    icons: set[str] = set()
    home = copy.get("home", {})
    if isinstance(home, dict):
        for item in home.get("start_cards", []):
            if isinstance(item, dict) and item.get("icon"):
                icons.add(str(item["icon"]))
    concepts = copy.get("concepts", {})
    if isinstance(concepts, dict):
        for item in concepts.get("items", []):
            if isinstance(item, list) and len(item) >= 3:
                icons.add(str(item[2]))
    governance = copy.get("governance", {})
    if isinstance(governance, dict):
        for item in governance.get("cards", []):
            if isinstance(item, list) and len(item) >= 3:
                icons.add(str(item[2]))
    for workflow in copy.get("workflows", []):
        if isinstance(workflow, dict) and workflow.get("icon"):
            icons.add(str(workflow["icon"]))
    role_icons = copy.get("role_icons", {})
    if isinstance(role_icons, dict):
        icons.update(str(value) for value in role_icons.values())
    for primitive in manifest.get("primitives", []):
        if isinstance(primitive, dict) and primitive.get("icon"):
            icons.add(str(primitive["icon"]))
    for workflow in manifest.get("workflows", []):
        if isinstance(workflow, dict) and workflow.get("icon"):
            icons.add(str(workflow["icon"]))
    return icons


def expected_primitives() -> dict[str, str]:
    expected: dict[str, str] = {}
    for path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        expected[f"skill:{path.parent.name}"] = path.relative_to(ROOT).as_posix()
    for path in sorted((ROOT / "agents").glob("*.md")):
        expected[f"agent:{path.stem}"] = path.relative_to(ROOT).as_posix()
    return expected


def fail(message: str) -> None:
    raise AssertionError(message)


def compare_dirs(expected: Path, actual: Path) -> list[str]:
    issues: list[str] = []
    comparison = filecmp.dircmp(expected, actual)
    for name in comparison.left_only:
        issues.append(f"missing generated path: {actual / name}")
    for name in comparison.right_only:
        issues.append(f"unexpected generated path: {actual / name}")
    for name in comparison.common_files:
        if not filecmp.cmp(expected / name, actual / name, shallow=False):
            issues.append(f"stale generated path: {actual / name}")
    for name in comparison.common_dirs:
        issues.extend(compare_dirs(expected / name, actual / name))
    return issues


def page_metadata(path: Path) -> tuple[str | None, str | None]:
    text = path.read_text(encoding="utf-8")
    primitive = re.search(r'<meta name="spellbook-primitive" content="([^"]+)">', text)
    source = re.search(r'<meta name="spellbook-source" content="([^"]+)">', text)
    return (
        primitive.group(1) if primitive else None,
        source.group(1) if source else None,
    )


def validate_site(site: Path, compare_to_rebuild: bool = True) -> None:
    if not site.exists():
        fail(f"{site}: missing; run scripts/build-docs-site.sh")

    copy = load_copy()
    expected = expected_primitives()
    seen: dict[str, list[Path]] = {}
    source_seen: dict[str, list[Path]] = {}
    pages = sorted((site / "reference").glob("*/*.html"))
    for page in pages:
        primitive, source = page_metadata(page)
        if primitive:
            seen.setdefault(primitive, []).append(page)
        if source:
            source_seen.setdefault(source, []).append(page)
            if not (ROOT / source).exists():
                fail(f"{page}: stale source link {source}")

    missing = sorted(set(expected) - set(seen))
    if missing:
        fail("missing primitive page(s): " + ", ".join(missing))
    extra = sorted(set(seen) - set(expected))
    if extra:
        fail("unexpected primitive page(s): " + ", ".join(extra))
    duplicates = {key: value for key, value in seen.items() if len(value) != 1}
    if duplicates:
        fail("duplicate primitive page(s): " + ", ".join(sorted(duplicates)))
    duplicate_sources = {key: value for key, value in source_seen.items() if len(value) != 1}
    if duplicate_sources:
        fail("duplicate source link(s): " + ", ".join(sorted(duplicate_sources)))

    manifest_path = site / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("copy_source") != "docs/copy/site.json":
        fail(f"{manifest_path}: copy_source must be docs/copy/site.json")
    manifest_ids = [item["id"] for item in manifest.get("primitives", [])]
    if sorted(manifest_ids) != sorted(expected):
        fail(f"{manifest_path}: primitive manifest does not match source catalog")
    for item in manifest.get("primitives", []):
        page = site / item["page"]
        source = ROOT / item["source"]
        if not page.exists():
            fail(f"{manifest_path}: page missing for {item['id']}: {item['page']}")
        if not source.exists():
            fail(f"{manifest_path}: source missing for {item['id']}: {item['source']}")

    required_pages = [
        "index.html",
        "concepts.html",
        "workflows.html",
        "governance.html",
        "reference/index.html",
        "reference/gates.html",
        "reference/bootstrap.html",
        "llms.txt",
        ".nojekyll",
    ]
    for relative in required_pages:
        path = site / relative
        if not path.exists():
            fail(f"{path}: missing required page")
        text = path.read_text(encoding="utf-8")
        if relative.endswith(".html") and GENERATED not in text:
            fail(f"{path}: missing generated marker")

    workflows = copy.get("workflows", [])
    if not isinstance(workflows, list) or len(workflows) < 5:
        fail(f"{COPY_SOURCE}: expected at least five workflows")
    expected_workflow_pages = {re.sub(r"[^a-z0-9-]+", "-", str(item.get("title", "")).lower()).strip("-") + ".html" for item in workflows if isinstance(item, dict)}
    workflow_pages = sorted((site / "workflows").glob("*.html"))
    workflow_page_names = {page.name for page in workflow_pages}
    if workflow_page_names != expected_workflow_pages:
        fail(f"{site / 'workflows'}: workflow pages do not match docs/copy/site.json")
    for page in workflow_pages:
        text = page.read_text(encoding="utf-8")
        for phrase in ["Input", "Decision", "Evidence", "Failure handling", "What to verify"]:
            if phrase not in text:
                fail(f"{page}: missing workflow section {phrase}")

    icons_path = site / "assets/icons.svg"
    if not icons_path.exists():
        fail(f"{icons_path}: missing generated icon sprite")
    icons_text = icons_path.read_text(encoding="utf-8")
    manifest_icons = set(manifest.get("icons", []))
    for icon in required_icons(copy, manifest):
        if icon not in manifest_icons:
            fail(f"{manifest_path}: icon {icon} is used but missing from manifest icons")
        if f'id="icon-{icon}"' not in icons_text:
            fail(f"{icons_path}: missing symbol for icon {icon}")

    for path in sorted(site.rglob("*")):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        for pattern in PRIVATE_PATTERNS:
            if pattern.search(text):
                fail(f"{path}: generated docs contain private or local-only text matching {pattern.pattern}")

    if compare_to_rebuild:
        with tempfile.TemporaryDirectory() as tmp:
            rebuilt = Path(tmp) / "site"
            subprocess.run(
                ["python3", "scripts/build-docs-site.py", "--output", str(rebuilt)],
                cwd=ROOT,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            issues = compare_dirs(rebuilt, site)
            if issues:
                fail("docs/site is stale:\n" + "\n".join(issues[:40]))


def expect_failure(site: Path, label: str) -> None:
    try:
        validate_site(site, compare_to_rebuild=False)
    except AssertionError:
        return
    fail(f"self-test did not fail for {label}")


def self_test() -> None:
    validate_site(SITE, compare_to_rebuild=True)
    skill_pages = sorted((SITE / "reference/skills").glob("*.html"))
    if not skill_pages:
        fail("self-test needs at least one generated skill page")
    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "site"
        shutil.copytree(SITE, base)
        skill_pages_tmp = sorted((base / "reference/skills").glob("*.html"))
        skill_pages_tmp[0].unlink()
        expect_failure(base, "missing generated skill page")

    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "site"
        shutil.copytree(SITE, base)
        skill_pages_tmp = sorted((base / "reference/skills").glob("*.html"))
        shutil.copy2(skill_pages_tmp[0], skill_pages_tmp[0].with_name("duplicate.html"))
        expect_failure(base, "duplicate generated primitive page")

    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "site"
        shutil.copytree(SITE, base)
        page = sorted((base / "reference/skills").glob("*.html"))[0]
        text = page.read_text(encoding="utf-8")
        text = re.sub(
            r'<meta name="spellbook-source" content="[^"]+">',
            '<meta name="spellbook-source" content="missing/source.md">',
            text,
            count=1,
        )
        page.write_text(text, encoding="utf-8")
        expect_failure(base, "stale source link")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, default=SITE)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    site = args.site if args.site.is_absolute() else ROOT / args.site
    if args.self_test:
        self_test()
    else:
        validate_site(site)
    print("docs/site: valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
