#!/usr/bin/env python3
"""Validate generated Harness Kit docs site output."""

from __future__ import annotations

import argparse
import filecmp
import hashlib
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "docs/site"
COPY_SOURCE = ROOT / "docs/copy/site.json"
COPY_IMAGE_ROOT = ROOT / "docs/copy/images"
SITE_IMAGE_ROOT = "assets/images"
GENERATED = "Generated by scripts/build-docs-site.py; do not edit manually."
PRIVATE_PATTERNS = [
    re.compile(r"/Users/[A-Za-z0-9_-]+/"),
    re.compile(r"\bdaybook\b", re.IGNORECASE),
    re.compile(r"provider-lanes/", re.IGNORECASE),
]


def load_copy() -> dict[str, object]:
    if not COPY_SOURCE.exists():
        fail(f"{COPY_SOURCE}: missing docs copy source")
    text = COPY_SOURCE.read_text(encoding="utf-8")
    for pattern in PRIVATE_PATTERNS:
        if pattern.search(text):
            fail(f"{COPY_SOURCE}: copy source contains private or local-only text matching {pattern.pattern}")
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        fail(f"{COPY_SOURCE}: invalid JSON: {exc}")
    for key in ["home", "concepts", "governance", "workflows", "role_icons"]:
        if key not in data:
            fail(f"{COPY_SOURCE}: missing required key {key}")
    return data


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")


def image_declarations(copy: dict[str, object]) -> list[dict[str, object]]:
    images = copy.get("images", [])
    if not isinstance(images, list):
        fail(f"{COPY_SOURCE}: images must be list")
    workflows = copy.get("workflows", [])
    workflow_pages = {
        f"workflows/{slug(str(item.get('title', '')))}.html"
        for item in workflows
        if isinstance(item, dict)
    }
    declarations: list[dict[str, object]] = []
    seen_sources: set[str] = set()
    seen_outputs: set[str] = set()
    seen_anchors: set[tuple[str, str]] = set()
    for index, raw in enumerate(images):
        if not isinstance(raw, dict):
            fail(f"{COPY_SOURCE}: images[{index}] must be object")
        image = dict(raw)
        required = [
            "page",
            "source",
            "alt",
            "text_equivalent_anchor",
            "text_equivalent_heading",
            "text_equivalent_items",
            "source_policy",
            "review_note",
            "regeneration_ref",
        ]
        missing = [key for key in required if key not in image]
        if missing:
            fail(f"{COPY_SOURCE}: images[{index}] missing {', '.join(missing)}")
        page = str(image["page"])
        source = str(image["source"])
        anchor = str(image["text_equivalent_anchor"])
        if page not in workflow_pages:
            fail(f"{COPY_SOURCE}: images[{index}] targets unknown workflow page {page}")
        if not source.startswith("docs/copy/images/") or Path(source).is_absolute() or ".." in Path(source).parts:
            fail(f"{COPY_SOURCE}: images[{index}] source must stay under docs/copy/images/")
        source_path = ROOT / source
        if not source_path.exists():
            fail(f"{source}: declared image source is missing")
        if source_path.suffix.lower() not in {".svg", ".png", ".jpg", ".jpeg", ".webp"}:
            fail(f"{source}: unsupported image extension")
        try:
            max_bytes = int(image.get("max_bytes", 250 * 1024))
        except (TypeError, ValueError):
            fail(f"{COPY_SOURCE}: images[{index}] max_bytes must be an integer")
        if max_bytes <= 0:
            fail(f"{COPY_SOURCE}: images[{index}] max_bytes must be positive")
        source_size = source_path.stat().st_size
        if source_size > max_bytes:
            fail(f"{source}: {source_size} bytes exceeds max_bytes {max_bytes}")
        if not re.fullmatch(r"[a-z][a-z0-9-]*", anchor):
            fail(f"{COPY_SOURCE}: images[{index}] text_equivalent_anchor must be a stable HTML id")
        items = image["text_equivalent_items"]
        if not isinstance(items, list) or not items or any(not str(item).strip() for item in items):
            fail(f"{COPY_SOURCE}: images[{index}] text_equivalent_items must be non-empty strings")
        for text_key in ["alt", "text_equivalent_heading", "source_policy", "review_note", "regeneration_ref"]:
            if not str(image[text_key]).strip():
                fail(f"{COPY_SOURCE}: images[{index}] {text_key} must be non-empty")
        output = f"{SITE_IMAGE_ROOT}/{source_path.name}"
        if source in seen_sources or output in seen_outputs or (page, anchor) in seen_anchors:
            fail(f"{COPY_SOURCE}: images[{index}] duplicates an image source, output, or anchor")
        seen_sources.add(source)
        seen_outputs.add(output)
        seen_anchors.add((page, anchor))
        image["output"] = output
        image["max_bytes"] = max_bytes
        declarations.append(image)

    declared_sources = {str(image["source"]) for image in declarations}
    if COPY_IMAGE_ROOT.exists():
        undeclared = [
            path.relative_to(ROOT).as_posix()
            for path in sorted(COPY_IMAGE_ROOT.rglob("*"))
            if path.is_file() and path.relative_to(ROOT).as_posix() not in declared_sources
        ]
        if undeclared:
            fail(f"{COPY_IMAGE_ROOT.relative_to(ROOT)}: undeclared source image(s): " + ", ".join(undeclared))
    return declarations


def image_manifest_row(image: dict[str, object]) -> dict[str, object]:
    source = str(image["source"])
    data = (ROOT / source).read_bytes()
    return {
        "page": str(image["page"]),
        "source": source,
        "output": str(image["output"]),
        "alt": str(image["alt"]),
        "text_equivalent_anchor": str(image["text_equivalent_anchor"]),
        "text_equivalent_heading": str(image["text_equivalent_heading"]),
        "text_equivalent_items": [str(item) for item in image["text_equivalent_items"]],
        "source_policy": str(image["source_policy"]),
        "review_note": str(image["review_note"]),
        "regeneration_ref": str(image["regeneration_ref"]),
        "max_bytes": int(image["max_bytes"]),
        "bytes": len(data),
        "sha256": hashlib.sha256(data).hexdigest(),
    }


def html_img_srcs(text: str) -> list[tuple[str, str]]:
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    tags = re.findall(r"<img\b[^>]*>", text, flags=re.IGNORECASE)
    found: list[tuple[str, str]] = []
    for tag in tags:
        src = re.search(r"""\bsrc\s*=\s*["']([^"']+)["']""", tag, flags=re.IGNORECASE)
        alt = re.search(r"""\balt\s*=\s*["']([^"']*)["']""", tag, flags=re.IGNORECASE)
        if src:
            found.append((src.group(1), alt.group(1) if alt else ""))
    return found


def validate_images(copy: dict[str, object], manifest: dict[str, object], site: Path) -> None:
    declarations = image_declarations(copy)
    expected_rows = [image_manifest_row(image) for image in declarations]
    if manifest.get("images", []) != expected_rows:
        fail(f"{site / 'manifest.json'}: image manifest does not match docs/copy/site.json")

    expected_outputs = {str(row["output"]) for row in expected_rows}
    generated_image_root = site / SITE_IMAGE_ROOT
    if generated_image_root.exists():
        extra = [
            path.relative_to(site).as_posix()
            for path in sorted(generated_image_root.rglob("*"))
            if path.is_file() and path.relative_to(site).as_posix() not in expected_outputs
        ]
        if extra:
            fail(f"{generated_image_root}: unexpected generated image(s): " + ", ".join(extra))
    elif expected_outputs:
        fail(f"{generated_image_root}: missing generated image directory")

    for image, row in zip(declarations, expected_rows):
        output = site / str(image["output"])
        source = ROOT / str(image["source"])
        if not output.exists():
            fail(f"{output}: declared generated image is missing")
        if output.read_bytes() != source.read_bytes():
            fail(f"{output}: generated image bytes drift from {image['source']}")
        page = site / str(image["page"])
        if not page.exists():
            fail(f"{page}: image target page is missing")
        text = page.read_text(encoding="utf-8")
        src = path_between_pages(str(image["page"]), str(image["output"]))
        matches = [(found_src, alt) for found_src, alt in html_img_srcs(text) if found_src == src]
        if len(matches) != 1:
            fail(f"{page}: declared image {src} must be used exactly once")
        if matches[0][1] != str(image["alt"]):
            fail(f"{page}: image alt text does not match docs/copy/site.json")
        if f'id="{image["text_equivalent_anchor"]}"' not in text:
            fail(f"{page}: missing text-equivalent anchor {image['text_equivalent_anchor']}")
        if str(image["review_note"]) not in text:
            fail(f"{page}: missing image review note")
        if str(image["text_equivalent_heading"]) not in text:
            fail(f"{page}: missing image text-equivalent heading")
        for item in image["text_equivalent_items"]:
            if str(item) not in text:
                fail(f"{page}: missing image text-equivalent item")
        for key in ["source_policy", "regeneration_ref"]:
            if str(image[key]) not in text:
                fail(f"{page}: missing image {key}")

    allowed_srcs_by_page = {
        str(image["page"]): {path_between_pages(str(image["page"]), str(image["output"]))}
        for image in declarations
    }
    for page in sorted(site.rglob("*.html")):
        relative_page = page.relative_to(site).as_posix()
        allowed_srcs = allowed_srcs_by_page.get(relative_page, set())
        for src, _alt in html_img_srcs(page.read_text(encoding="utf-8")):
            if src not in allowed_srcs:
                fail(f"{page}: undeclared img src {src}")


def path_between_pages(page: str, target: str) -> str:
    page_dir = Path(page).parent
    if str(page_dir) == ".":
        return target
    return "/".join([".."] * len(page_dir.parts) + [target])


def required_icons(copy: dict[str, object], manifest: dict[str, object]) -> set[str]:
    icons: set[str] = set()
    home = copy.get("home", {})
    if isinstance(home, dict):
        for item in home.get("start_cards", []):
            if isinstance(item, dict) and item.get("icon"):
                icons.add(str(item["icon"]))
    concepts = copy.get("concepts", {})
    if isinstance(concepts, dict):
        for item in concepts.get("items", []):
            if isinstance(item, list) and len(item) >= 3:
                icons.add(str(item[2]))
    governance = copy.get("governance", {})
    if isinstance(governance, dict):
        for item in governance.get("cards", []):
            if isinstance(item, list) and len(item) >= 3:
                icons.add(str(item[2]))
    for workflow in copy.get("workflows", []):
        if isinstance(workflow, dict) and workflow.get("icon"):
            icons.add(str(workflow["icon"]))
    role_icons = copy.get("role_icons", {})
    if isinstance(role_icons, dict):
        icons.update(str(value) for value in role_icons.values())
    for primitive in manifest.get("primitives", []):
        if isinstance(primitive, dict) and primitive.get("icon"):
            icons.add(str(primitive["icon"]))
    for workflow in manifest.get("workflows", []):
        if isinstance(workflow, dict) and workflow.get("icon"):
            icons.add(str(workflow["icon"]))
    return icons


def expected_primitives() -> dict[str, str]:
    expected: dict[str, str] = {}
    for path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        expected[f"skill:{path.parent.name}"] = path.relative_to(ROOT).as_posix()
    for path in sorted((ROOT / "agents").glob("*.md")):
        expected[f"agent:{path.stem}"] = path.relative_to(ROOT).as_posix()
    return expected


def fail(message: str) -> None:
    raise AssertionError(message)


def compare_dirs(expected: Path, actual: Path) -> list[str]:
    issues: list[str] = []
    comparison = filecmp.dircmp(expected, actual)
    for name in comparison.left_only:
        issues.append(f"missing generated path: {actual / name}")
    for name in comparison.right_only:
        issues.append(f"unexpected generated path: {actual / name}")
    for name in comparison.common_files:
        if not filecmp.cmp(expected / name, actual / name, shallow=False):
            issues.append(f"stale generated path: {actual / name}")
    for name in comparison.common_dirs:
        issues.extend(compare_dirs(expected / name, actual / name))
    return issues


def page_metadata(path: Path) -> tuple[str | None, str | None]:
    text = path.read_text(encoding="utf-8")
    primitive = re.search(r'<meta name="harness-kit-primitive" content="([^"]+)">', text)
    source = re.search(r'<meta name="harness-kit-source" content="([^"]+)">', text)
    return (
        primitive.group(1) if primitive else None,
        source.group(1) if source else None,
    )


def validate_site(site: Path, compare_to_rebuild: bool = True) -> None:
    if not site.exists():
        fail(f"{site}: missing; run scripts/build-docs-site.sh")

    copy = load_copy()
    expected = expected_primitives()
    seen: dict[str, list[Path]] = {}
    source_seen: dict[str, list[Path]] = {}
    pages = sorted((site / "reference").glob("*/*.html"))
    for page in pages:
        primitive, source = page_metadata(page)
        if primitive:
            seen.setdefault(primitive, []).append(page)
        if source:
            source_seen.setdefault(source, []).append(page)
            if not (ROOT / source).exists():
                fail(f"{page}: stale source link {source}")

    missing = sorted(set(expected) - set(seen))
    if missing:
        fail("missing primitive page(s): " + ", ".join(missing))
    extra = sorted(set(seen) - set(expected))
    if extra:
        fail("unexpected primitive page(s): " + ", ".join(extra))
    duplicates = {key: value for key, value in seen.items() if len(value) != 1}
    if duplicates:
        fail("duplicate primitive page(s): " + ", ".join(sorted(duplicates)))
    duplicate_sources = {key: value for key, value in source_seen.items() if len(value) != 1}
    if duplicate_sources:
        fail("duplicate source link(s): " + ", ".join(sorted(duplicate_sources)))

    manifest_path = site / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("copy_source") != "docs/copy/site.json":
        fail(f"{manifest_path}: copy_source must be docs/copy/site.json")
    manifest_ids = [item["id"] for item in manifest.get("primitives", [])]
    if sorted(manifest_ids) != sorted(expected):
        fail(f"{manifest_path}: primitive manifest does not match source catalog")
    for item in manifest.get("primitives", []):
        page = site / item["page"]
        source = ROOT / item["source"]
        if not page.exists():
            fail(f"{manifest_path}: page missing for {item['id']}: {item['page']}")
        if not source.exists():
            fail(f"{manifest_path}: source missing for {item['id']}: {item['source']}")
    validate_images(copy, manifest, site)

    required_pages = [
        "index.html",
        "concepts.html",
        "workflows.html",
        "governance.html",
        "reference/index.html",
        "reference/gates.html",
        "reference/bootstrap.html",
        "llms.txt",
        ".nojekyll",
    ]
    for relative in required_pages:
        path = site / relative
        if not path.exists():
            fail(f"{path}: missing required page")
        text = path.read_text(encoding="utf-8")
        if relative.endswith(".html") and GENERATED not in text:
            fail(f"{path}: missing generated marker")

    workflows = copy.get("workflows", [])
    if not isinstance(workflows, list) or len(workflows) < 5:
        fail(f"{COPY_SOURCE}: expected at least five workflows")
    expected_workflow_pages = {re.sub(r"[^a-z0-9-]+", "-", str(item.get("title", "")).lower()).strip("-") + ".html" for item in workflows if isinstance(item, dict)}
    workflow_pages = sorted((site / "workflows").glob("*.html"))
    workflow_page_names = {page.name for page in workflow_pages}
    if workflow_page_names != expected_workflow_pages:
        fail(f"{site / 'workflows'}: workflow pages do not match docs/copy/site.json")
    for page in workflow_pages:
        text = page.read_text(encoding="utf-8")
        for phrase in ["Input", "Decision", "Evidence", "Failure handling", "What to verify"]:
            if phrase not in text:
                fail(f"{page}: missing workflow section {phrase}")

    icons_path = site / "assets/icons.svg"
    if not icons_path.exists():
        fail(f"{icons_path}: missing generated icon sprite")
    icons_text = icons_path.read_text(encoding="utf-8")
    manifest_icons = set(manifest.get("icons", []))
    for icon in required_icons(copy, manifest):
        if icon not in manifest_icons:
            fail(f"{manifest_path}: icon {icon} is used but missing from manifest icons")
        if f'id="icon-{icon}"' not in icons_text:
            fail(f"{icons_path}: missing symbol for icon {icon}")

    for path in sorted(site.rglob("*")):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        for pattern in PRIVATE_PATTERNS:
            if pattern.search(text):
                fail(f"{path}: generated docs contain private or local-only text matching {pattern.pattern}")

    if compare_to_rebuild:
        with tempfile.TemporaryDirectory() as tmp:
            rebuilt = Path(tmp) / "site"
            subprocess.run(
                ["python3", "scripts/build-docs-site.py", "--output", str(rebuilt)],
                cwd=ROOT,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            issues = compare_dirs(rebuilt, site)
            if issues:
                fail("docs/site is stale:\n" + "\n".join(issues[:40]))


def expect_failure(site: Path, label: str) -> None:
    try:
        validate_site(site, compare_to_rebuild=False)
    except AssertionError:
        return
    fail(f"self-test did not fail for {label}")


def expect_copy_failure(copy: dict[str, object], label: str) -> None:
    try:
        image_declarations(copy)
    except AssertionError:
        return
    fail(f"self-test did not fail for {label}")


def mutated_copy(mutator) -> dict[str, object]:
    copy = json.loads(COPY_SOURCE.read_text(encoding="utf-8"))
    mutator(copy)
    return copy


def self_test() -> None:
    validate_site(SITE, compare_to_rebuild=True)
    copy = load_copy()
    images = image_declarations(copy)
    skill_pages = sorted((SITE / "reference/skills").glob("*.html"))
    if not skill_pages:
        fail("self-test needs at least one generated skill page")
    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "site"
        shutil.copytree(SITE, base)
        skill_pages_tmp = sorted((base / "reference/skills").glob("*.html"))
        skill_pages_tmp[0].unlink()
        expect_failure(base, "missing generated skill page")

    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "site"
        shutil.copytree(SITE, base)
        skill_pages_tmp = sorted((base / "reference/skills").glob("*.html"))
        shutil.copy2(skill_pages_tmp[0], skill_pages_tmp[0].with_name("duplicate.html"))
        expect_failure(base, "duplicate generated primitive page")

    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "site"
        shutil.copytree(SITE, base)
        page = sorted((base / "reference/skills").glob("*.html"))[0]
        text = page.read_text(encoding="utf-8")
        text = re.sub(
            r'<meta name="harness-kit-source" content="[^"]+">',
            '<meta name="harness-kit-source" content="missing/source.md">',
            text,
            count=1,
        )
        page.write_text(text, encoding="utf-8")
        expect_failure(base, "stale source link")

    if images:
        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp) / "site"
            shutil.copytree(SITE, base)
            image_path = next((base / SITE_IMAGE_ROOT).glob("*"))
            image_path.unlink()
            expect_failure(base, "missing generated image")

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp) / "site"
            shutil.copytree(SITE, base)
            image_path = next((base / SITE_IMAGE_ROOT).glob("*"))
            image_path.write_text(image_path.read_text(encoding="utf-8") + "\n<!-- drift -->\n", encoding="utf-8")
            expect_failure(base, "generated image byte drift")

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp) / "site"
            shutil.copytree(SITE, base)
            page = base / str(images[0]["page"])
            text = page.read_text(encoding="utf-8")
            text = re.sub(r'alt="[^"]+"', 'alt=""', text, count=1)
            page.write_text(text, encoding="utf-8")
            expect_failure(base, "empty or mismatched image alt")

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp) / "site"
            shutil.copytree(SITE, base)
            page = base / str(images[0]["page"])
            text = page.read_text(encoding="utf-8").replace(
                f'id="{images[0]["text_equivalent_anchor"]}"',
                'id="missing-anchor"',
            )
            page.write_text(text, encoding="utf-8")
            expect_failure(base, "missing text-equivalent anchor")

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp) / "site"
            shutil.copytree(SITE, base)
            page = base / str(images[0]["page"])
            text = page.read_text(encoding="utf-8").replace("</section>", '<img src="../assets/images/undeclared.svg" alt="Undeclared">\n</section>', 1)
            page.write_text(text, encoding="utf-8")
            expect_failure(base, "undeclared html image")

        with tempfile.TemporaryDirectory() as tmp:
            base = Path(tmp) / "site"
            shutil.copytree(SITE, base)
            extra = base / SITE_IMAGE_ROOT / "stale.svg"
            extra.write_text("<svg xmlns=\"http://www.w3.org/2000/svg\"/>", encoding="utf-8")
            expect_failure(base, "stale generated image")

        expect_copy_failure(mutated_copy(lambda copy: copy["images"][0].pop("source_policy")), "missing source policy")
        expect_copy_failure(mutated_copy(lambda copy: copy["images"][0].update({"review_note": ""})), "missing review note")
        expect_copy_failure(mutated_copy(lambda copy: copy["images"][0].update({"source": "../secrets.svg"})), "image path traversal")
        expect_copy_failure(mutated_copy(lambda copy: copy["images"][0].update({"page": "workflows/missing.html"})), "unused image declaration")
        expect_copy_failure(mutated_copy(lambda copy: copy["images"][0].update({"max_bytes": 1})), "image size overflow")

        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            shutil.copytree(
                ROOT,
                repo,
                ignore=shutil.ignore_patterns(
                    ".agents",
                    ".antigravitycli",
                    ".claude",
                    ".codex",
                    ".git",
                    ".pi",
                    "__pycache__",
                    ".venv",
                    "skills/.external",
                ),
            )
            copy_path = repo / "docs/copy/site.json"
            data = json.loads(copy_path.read_text(encoding="utf-8"))
            data.pop("images", None)
            copy_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            image_root = repo / "docs/copy/images"
            if image_root.exists():
                shutil.rmtree(image_root)
            subprocess.run(
                ["bash", "scripts/build-docs-site.sh"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            subprocess.run(
                ["python3", "scripts/check-docs-site.py"],
                cwd=repo,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, default=SITE)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    site = args.site if args.site.is_absolute() else ROOT / args.site
    if args.self_test:
        self_test()
    else:
        validate_site(site)
    print("docs/site: valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
